// AUTO-GENERATED by scripts/translate meta workflow — localized SEO title/description
// for the guide / faq / creators / tools pages that were missing from seo-i18n.ts.
// English source of truth lives in PAGE_SEO (seo.ts); this overlay is deep-merged
// under PAGE_SEO_I18N by resolveSeo(). Regenerate rather than hand-editing.
import type { PageSeo } from './seo'

export const PAGE_SEO_I18N_GUIDES: Record<string, Record<string, PageSeo>> = {
  "es": {
    "/guides": {
      "title": "Guías de Warframe — Farmeo, builds, platino y ayuda para novatos",
      "description": "Todas las guías de Warframe en un sitio: ayuda para nuevos jugadores, farmeo de platino y recursos, builds, endgame y unas FAQ con buscador. Basado en r/Warframe y gratis para Tenno."
    },
    "/guides/farming": {
      "title": "Centro de farmeo de Warframe — Busca cualquier objeto o recurso",
      "description": "¿Qué quieres farmear? Busca por tipo — Orokin Cells, Kuva, piezas Prime, Argon, créditos, Endo — y ve al mejor farmeo. Todas las guías de farmeo de Warframe en un solo centro."
    },
    "/faq": {
      "title": "FAQ de Warframe — Respuestas a las dudas de siempre",
      "description": "Las FAQ de r/Warframe, respondidas: frames de inicio, ganar platino, trading, farmeo, Steel Path, mods y más. Con buscador, enlazadas entre sí y siempre gratis."
    },
    "/creators": {
      "title": "Mejores youtubers y creadores de Warframe a seguir",
      "description": "Un directorio verificado de los mejores creadores de contenido de Warframe: maestros de builds, autores de tier lists, especialistas en farmeo y guías para novatos que seguir en YouTube."
    },
    "/tools": {
      "title": "Directorio de herramientas de Warframe — Mejores apps y webs",
      "description": "El directorio verificado de las mejores herramientas de Warframe de terceros: trading, planificadores de builds, tablas de drops, calculadoras de rivens, world-state trackers, apps y bots de Discord."
    },
    "/tools/best": {
      "title": "Mejores herramientas de Warframe 2026 — Ranking verificado",
      "description": "Las mejores herramientas de Warframe de terceros, en ranking y verificadas: trading y comprobadores de precios, planificadores de builds, tablas de drops, trackers de rivens y world-state. Cuáles usar y por qué."
    },
    "/guides/new-player": {
      "title": "Guía de novato en Warframe 2026: qué hacer primero",
      "description": "Una guía completa para principiantes en Warframe: qué hacer primero, cómo funciona el mapa estelar, qué frame farmear y los errores que evitar. Empieza Warframe con buen pie."
    },
    "/guides/beginner-warframes": {
      "title": "Mejores Warframes para novatos 2026 — Cuál elegir primero",
      "description": "Qué Warframe de inicio elegir (Excalibur, Mag, Volt), qué frame farmear primero (Rhino) y dónde caen los frames fáciles del principio. Una hoja de ruta para novatos."
    },
    "/guides/progression": {
      "title": "Guía de progresión en Warframe 2026 — Qué hacer ahora",
      "description": "La hoja de ruta de progresión de Warframe: mapa estelar, Junctions, Mastery Rank y una checklist fase a fase de qué hacer después. Deja de sentirte perdido, Tenno."
    },
    "/guides/mastery-rank": {
      "title": "Guía de Mastery Rank en Warframe — Subir de nivel rápido",
      "description": "Qué desbloquea el Mastery Rank, cómo funciona la afinidad y su reparto, y las formas más rápidas de subir armas y frames en Warframe. Sube tu MR de forma eficiente."
    },
    "/guides/quests": {
      "title": "Orden de misiones de Warframe — Guía de historia sin spoilers",
      "description": "El orden recomendado para jugar las misiones de historia de Warframe, desde Vor's Prize hasta The New War y 1999 — qué desbloquea cada misión, con mínimos spoilers."
    },
    "/guides/platinum": {
      "title": "Cómo conseguir platino en Warframe (free-to-play)",
      "description": "Consigue platino en Warframe gratis: qué se vende, cómo funciona el trading y cómo poner precio a piezas Prime, mods y rivens. El farmeo de platino free-to-play, explicado."
    },
    "/guides/credits": {
      "title": "Farmeo de créditos en Warframe — Mejores métodos y nodos",
      "description": "Los mejores farmeos de créditos de Warframe por fase — The Index, Profit-Taker y boosters — y de dónde salen los millones. Farmea créditos rápido y sin fallar."
    },
    "/guides/focus": {
      "title": "Guía de farmeo de Focus en Warframe — Mejores métodos",
      "description": "Cómo farmear Focus en Warframe: desbloquea al Operator, elige escuela y usa los mejores farmeos, lentes y esferas de convergencia. Sube tus escuelas de forma eficiente."
    },
    "/guides/kuva": {
      "title": "Guía de farmeo de Kuva en Warframe — Métodos rápidos",
      "description": "Las mejores formas de farmear Kuva en Warframe para re-rolls de rivens y armas Kuva — misiones de Survival, Siphon y Flood, boosters y tasas realistas."
    },
    "/guides/relics": {
      "title": "Guía de farmeo de Relic y Void Trace en Warframe",
      "description": "Cómo funcionan las Void Relics y las Void Traces en Warframe: abrir fisuras, refinar a Radiant, recompensas compartidas y farmeo eficiente de piezas Prime."
    },
    "/guides/resources": {
      "title": "Farmeo de recursos en Warframe — Dónde farmear todo",
      "description": "Dónde farmear cada recurso clave de Warframe: Orokin Cells, Neurodes, Argon Crystals, Tellurium, Oxium, Nitain y más. Una tabla de referencia de farmeo completa."
    },
    "/guides/standing": {
      "title": "Guía de standing y syndicates en Warframe",
      "description": "Alcanza tu tope diario de standing en cada syndicate y facción de mundo abierto de Warframe. Cómo funciona el límite de reputación y las formas más rápidas de maximizarlo."
    },
    "/guides/mods": {
      "title": "Guía de mods en Warframe — Mods esenciales y supervivencia",
      "description": "Cómo funciona el modding en Warframe, los mods imprescindibles y el shield-gating para dejar de morir. Entiende la capacidad de mods, las polaridades y los multiplicadores de daño."
    },
    "/guides/helminth": {
      "title": "Guía de Helminth en Warframe — Subsumir y mejores habilidades",
      "description": "Cómo funciona el sistema Helminth de Warframe: desbloquearlo, subsumir habilidades y los mejores poderes para injertar en tus frames. El buildcrafting, explicado."
    },
    "/guides/arcanes": {
      "title": "Guía de arcanes en Warframe — Mejores arcanes y cómo farmear",
      "description": "Qué hacen los arcanes en Warframe, cómo subirlos de rango, dónde caen y los arcanes básicos que merece la pena farmear. Potencia tus frames, armas y operator."
    },
    "/guides/riven": {
      "title": "Rivens de Warframe explicados — Disposition y re-rolls",
      "description": "Todo sobre los rivens de Warframe: disposition, re-rolls con Kuva, valoración, rivens velados y por qué los rivens malos son Endo barato. Nociones básicas de trading de rivens."
    },
    "/guides/steel-path": {
      "title": "Guía de Steel Path en Warframe — Desbloqueo y Steel Essence",
      "description": "Cómo desbloquear el Steel Path en Warframe, sobrevivir a él y farmear Steel Essence para adaptadores Incarnon, arcanes, Kuva y más. La guía de recompensas del modo difícil."
    },
    "/guides/eidolon": {
      "title": "Guía de caza de Eidolon en Warframe — Bases del Tridolon",
      "description": "Cómo cazar Eidolons en Warframe: amps, el escuadrón meta y pasar de un Teralyst en solitario al Tridolon completo. Farmea arcanes y focus rápido."
    },
    "/guides/railjack": {
      "title": "Guía de Railjack en Warframe — Desbloqueo, Intrinsics y farmeo",
      "description": "Cómo desbloquear y usar el Railjack en Warframe: monta tu nave, sube los Intrinsics y convierte el combate espacial en un farmeo de afinidad y recursos."
    },
    "/guides/duviri": {
      "title": "Guía de Duviri Paradox en Warframe — Circuit y Decrees",
      "description": "Cómo funciona la Duviri Paradox en Warframe: el Circuit roguelike, los Decrees y las recompensas semanales de Warframe e Incarnon. Jugable desde el principio."
    },
    "/guides/archon-shards": {
      "title": "Guía de Archon Shards en Warframe — Farmeo y mejores stats",
      "description": "Qué hacen los Archon Shards en Warframe, cómo farmearlos en el Archon Hunt semanal y qué stats priorizar. La mejora de poder de endgame, explicada."
    },
    "/guides/tier-list": {
      "title": "Tier list de Warframe 2026 — Cómo leerla de verdad",
      "description": "Por qué las tier lists de Warframe no coinciden, qué significa \"bueno\" según la actividad y unos cuantos frames fuertes en general. Juega con lo que disfrutas, no solo el meta."
    }
  },
  "pt": {
    "/guides": {
      "title": "Guias de Warframe — Farm, Builds, Platino e Iniciantes",
      "description": "Todo guia de Warframe em um só lugar: ajuda para novatos, farm de platino e recursos, builds, endgame e um FAQ pesquisável. Baseado no r/Warframe, grátis para Tenno."
    },
    "/guides/farming": {
      "title": "Central de Farm Warframe — Busque Qualquer Item ou Recurso",
      "description": "O que você quer farmar? Busque por tipo de item — Orokin Cells, Kuva, peças prime, Argon, créditos, Endo — e vá direto ao melhor farm. Todos os guias de farm de Warframe em uma central."
    },
    "/faq": {
      "title": "FAQ de Warframe — Respostas às Dúvidas Mais Comuns",
      "description": "O FAQ do r/Warframe respondido: frames iniciais, ganhar platino, trade, farm, Steel Path, mods e mais. Pesquisável, com links cruzados e sempre grátis."
    },
    "/creators": {
      "title": "Melhores YouTubers e Criadores de Warframe para Seguir",
      "description": "Um diretório verificado dos melhores criadores de conteúdo de Warframe — mestres de builds, criadores de tier list, especialistas em farm e guias para iniciantes no YouTube."
    },
    "/tools": {
      "title": "Diretório de Ferramentas Warframe — Melhores Apps e Sites",
      "description": "O diretório verificado das melhores ferramentas de terceiros de Warframe: trade, planejadores de build, drop tables, calculadoras de riven, rastreadores de world-state, apps e bots de Discord."
    },
    "/tools/best": {
      "title": "Melhores Ferramentas Warframe 2026 — Ranqueadas e Verificadas",
      "description": "As melhores ferramentas de terceiros de Warframe, ranqueadas e verificadas: trade e checadores de preço, planejadores de build, drop tables, rastreadores de riven e world-state. O que usar e por quê."
    },
    "/guides/new-player": {
      "title": "Guia de Iniciante Warframe 2026: Por Onde Começar",
      "description": "Um guia completo de Warframe para iniciantes: o que fazer primeiro, como funciona o star chart, qual frame farmar e os erros a evitar. Comece Warframe do jeito certo."
    },
    "/guides/beginner-warframes": {
      "title": "Melhores Warframes Iniciais 2026 — Qual Escolher Primeiro",
      "description": "Qual Warframe inicial escolher (Excalibur, Mag, Volt), qual frame farmar primeiro (Rhino) e onde os frames fáceis dropam no início. Um roteiro para iniciantes."
    },
    "/guides/progression": {
      "title": "Guia de Progressão Warframe 2026 — O Que Fazer Agora",
      "description": "O roteiro de progressão de Warframe: star chart, Junctions, Mastery Rank e um checklist etapa por etapa do que fazer a seguir. Pare de se sentir perdido, Tenno."
    },
    "/guides/mastery-rank": {
      "title": "Guia de Mastery Rank Warframe — Level Rápido e Afinidade",
      "description": "O que o Mastery Rank desbloqueia, como funciona a afinidade e o compartilhamento, e as formas mais rápidas de upar armas e frames em Warframe. Suba seu MR com eficiência."
    },
    "/guides/quests": {
      "title": "Ordem das Quests Warframe — Guia da História (Sem Spoiler)",
      "description": "A ordem recomendada para jogar as story quests de Warframe, de Vor's Prize a The New War e 1999 — quais quests desbloqueiam o quê, com o mínimo de spoilers."
    },
    "/guides/platinum": {
      "title": "Como Ganhar Platino em Warframe (Free-to-Play)",
      "description": "Ganhe platino em Warframe de graça: o que vende, como funciona o trade e como precificar peças prime, mods e rivens. Farm de platino free-to-play, explicado."
    },
    "/guides/credits": {
      "title": "Farm de Créditos Warframe — Melhores Métodos e Nodes",
      "description": "Os melhores farms de créditos de Warframe por etapa — The Index, Profit-Taker e boosters — além de onde vêm os milhões. Farme créditos rápido e com confiança."
    },
    "/guides/focus": {
      "title": "Guia de Farm de Focus Warframe — Melhores Métodos",
      "description": "Como farmar Focus em Warframe: desbloqueie o Operator, escolha uma escola e use os melhores farms de focus, lentes e orbes de convergência. Suba suas escolas com eficiência."
    },
    "/guides/kuva": {
      "title": "Guia de Farm de Kuva Warframe — Métodos Rápidos",
      "description": "As melhores formas de farmar Kuva em Warframe para re-rolls de riven e armas Kuva — missões de Survival, Siphon e Flood, boosters e taxas realistas."
    },
    "/guides/relics": {
      "title": "Guia de Farm de Relic e Void Trace Warframe",
      "description": "Como funcionam os Void Relics e Void Traces em Warframe: abrir fissures, refinar para Radiant, recompensas compartilhadas e farm eficiente de peças prime."
    },
    "/guides/resources": {
      "title": "Farm de Recursos Warframe — Onde Farmar Tudo",
      "description": "Onde farmar cada recurso essencial de Warframe: Orokin Cells, Neurodes, Argon Crystals, Tellurium, Oxium, Nitain e mais. Uma tabela de referência de farm completa."
    },
    "/guides/standing": {
      "title": "Guia de Farm de Standing e Syndicate Warframe",
      "description": "Bata o limite diário de standing em cada syndicate e facção de mundo aberto de Warframe. Como funciona o limite de reputação e as formas mais rápidas de maximizá-lo."
    },
    "/guides/mods": {
      "title": "Guia de Mods Warframe — Mods Essenciais e Sobrevivência",
      "description": "Como funciona a modding em Warframe, os mods indispensáveis e o shield-gating para parar de morrer. Entenda capacidade de mods, polaridades e os multiplicadores de dano."
    },
    "/guides/helminth": {
      "title": "Guia de Helminth Warframe — Subsume e Melhores Habilidades",
      "description": "Como funciona o sistema Helminth de Warframe: desbloqueá-lo, fazer subsume de habilidades e os melhores poderes para enxertar nos seus frames. Buildcrafting, explicado."
    },
    "/guides/arcanes": {
      "title": "Guia de Arcanes Warframe — Melhores Arcanes e Como Farmar",
      "description": "O que os arcanes fazem em Warframe, como upá-los, onde dropam e os arcanes essenciais que valem a pena farmar. Turbine seus frames, armas e operator."
    },
    "/guides/riven": {
      "title": "Riven Mods Warframe Explicados — Disposition e Rolls",
      "description": "Tudo sobre riven mods de Warframe: disposition, roll com Kuva, avaliação, rivens veiled e por que rivens ruins são Endo barato. O básico do trade de riven."
    },
    "/guides/steel-path": {
      "title": "Guia de Steel Path Warframe — Desbloqueio e Steel Essence",
      "description": "Como desbloquear o Steel Path em Warframe, sobreviver a ele e farmar Steel Essence para adaptadores incarnon, arcanes, kuva e mais. O guia de recompensas do hard mode."
    },
    "/guides/eidolon": {
      "title": "Guia de Caça a Eidolon Warframe — Básico do Tridolon",
      "description": "Como caçar Eidolons em Warframe: amps, o squad meta e a evolução do Teralyst solo até o Tridolon completo. Farme arcanes e focus rápido."
    },
    "/guides/railjack": {
      "title": "Guia de Railjack Warframe — Desbloqueio, Intrinsics e Farm",
      "description": "Como desbloquear e usar o Railjack em Warframe: monte sua nave, suba os Intrinsics e transforme o combate espacial em um farm de afinidade e recursos."
    },
    "/guides/duviri": {
      "title": "Guia do Duviri Paradox Warframe — Circuit e Decrees",
      "description": "Como funciona o Duviri Paradox em Warframe: o Circuit roguelike, os Decrees e as recompensas semanais de Warframe e Incarnon. Jogável desde o início."
    },
    "/guides/archon-shards": {
      "title": "Guia de Archon Shards Warframe — Farm e Melhores Stats",
      "description": "O que os Archon Shards fazem em Warframe, como farmá-los na Archon Hunt semanal e quais stats priorizar. O boost de poder do endgame, explicado."
    },
    "/guides/tier-list": {
      "title": "Tier List de Warframe 2026 — Como Realmente Interpretá-la",
      "description": "Por que as tier lists de Warframe discordam, o que \"bom\" realmente significa por atividade e alguns frames fortes em geral. Faça a build que você curte, não só a meta."
    }
  },
  "de": {
    "/guides": {
      "title": "Warframe Guides — Farming, Builds, Platin & Einsteiger",
      "description": "Alle Warframe-Guides an einem Ort: Hilfe für neue Spieler, Platin- und Ressourcen-Farming, Builds, Endgame und eine durchsuchbare FAQ. Basierend auf r/Warframe, gratis für Tenno."
    },
    "/guides/farming": {
      "title": "Warframe Farming-Hub — Jedes Item & jede Ressource",
      "description": "Was willst du farmen? Suche nach Item-Typ — Orokin Cells, Kuva, Prime-Teile, Argon, Credits, Endo — und spring zum besten Farm. Jeder Warframe-Farming-Guide in einem Hub."
    },
    "/faq": {
      "title": "Warframe FAQ — Antworten auf die häufigsten Fragen",
      "description": "Die r/Warframe FAQ, beantwortet: Starter-Frames, Platin verdienen, Handel, Farming, Steel Path, Mods und mehr. Durchsuchbar, verlinkt und immer gratis."
    },
    "/creators": {
      "title": "Beste Warframe YouTuber & Content Creator",
      "description": "Ein geprüftes Verzeichnis der besten Warframe Content Creator — Build-Meister, Tier-Listen-Macher, Farming-Spezialisten und Einsteiger-Guides, denen du auf YouTube folgen solltest."
    },
    "/tools": {
      "title": "Warframe Tools-Verzeichnis — Beste Community-Apps",
      "description": "Das geprüfte Verzeichnis der besten Warframe-Tools von Drittanbietern: Handel, Build-Planer, Drop-Tabellen, Riven-Rechner, World-State-Tracker, Apps und Discord-Bots."
    },
    "/tools/best": {
      "title": "Beste Warframe Tools 2026 — Gerankt & geprüft",
      "description": "Die besten Warframe-Tools von Drittanbietern, gerankt und geprüft: Handel und Preis-Checker, Build-Planer, Drop-Tabellen, Riven- und World-State-Tracker. Was du nutzen solltest und warum."
    },
    "/guides/new-player": {
      "title": "Warframe Einsteiger-Guide 2026: Was zuerst tun?",
      "description": "Ein kompletter Warframe-Einsteiger-Guide: Was du zuerst tun solltest, wie die Sternenkarte funktioniert, welchen Frame du farmen solltest und welche Fehler du vermeiden musst. Starte Warframe richtig."
    },
    "/guides/beginner-warframes": {
      "title": "Beste Anfänger-Warframes 2026 — Welchen zuerst?",
      "description": "Welchen Starter-Warframe du wählen solltest (Excalibur, Mag, Volt), welchen Frame du zuerst farmst (Rhino) und wo die einfachen frühen Frames droppen. Ein Fahrplan für Einsteiger."
    },
    "/guides/progression": {
      "title": "Warframe Progression-Guide 2026 — Wie geht's weiter?",
      "description": "Der Warframe-Fahrplan zum Fortschritt: Sternenkarte, Junctions, Mastery Rank und eine Schritt-für-Schritt-Checkliste, wie es weitergeht. Schluss mit dem Verlorensein, Tenno."
    },
    "/guides/mastery-rank": {
      "title": "Warframe Mastery Rank Guide — Schnelles Leveln",
      "description": "Was Mastery Rank freischaltet, wie Affinität und ihre Verteilung funktionieren und die schnellsten Wege, Waffen und Frames in Warframe zu leveln. Steigere deinen MR effizient."
    },
    "/guides/quests": {
      "title": "Warframe Quest-Reihenfolge — Story-Guide (spoilerarm)",
      "description": "Die empfohlene Reihenfolge für Warframes Story-Quests, von Vor's Prize über The New War bis 1999 — welche Quest was freischaltet, mit minimalen Spoilern."
    },
    "/guides/platinum": {
      "title": "Platin in Warframe verdienen (Free-to-Play)",
      "description": "Verdiene Warframe-Platin kostenlos: Was sich verkauft, wie der Handel funktioniert und wie du Prime-Teile, Mods und Rivens bepreist. Free-to-Play Platin-Farming erklärt."
    },
    "/guides/credits": {
      "title": "Warframe Credit-Farming — Beste Methoden & Nodes",
      "description": "Die besten Warframe Credit-Farms nach Fortschritt — The Index, Profit-Taker und Booster — plus woher die Millionen kommen. Farme Credits schnell und zuverlässig."
    },
    "/guides/focus": {
      "title": "Warframe Focus-Farming Guide — Beste Methoden",
      "description": "Wie du Focus in Warframe farmst: Schalte den Operator frei, wähle eine Schule und nutze die besten Focus-Farms, Linsen und Konvergenz-Kugeln. Level deine Schulen effizient."
    },
    "/guides/kuva": {
      "title": "Warframe Kuva-Farming Guide — Schnelle Methoden",
      "description": "Die besten Wege, Kuva in Warframe zu farmen für Riven-Neuwürfe und Kuva-Waffen — Survival-, Siphon- und Flood-Missionen, Booster und realistische Raten."
    },
    "/guides/relics": {
      "title": "Warframe Relic & Void Trace Farming Guide",
      "description": "Wie Void Relics und Void Traces in Warframe funktionieren: Fissures knacken, auf Radiant verfeinern, geteilte Belohnungen und effizientes Farming für Prime-Teile."
    },
    "/guides/resources": {
      "title": "Warframe Ressourcen-Farming — Wo du alles farmst",
      "description": "Wo du jede wichtige Warframe-Ressource farmst: Orokin Cells, Neurodes, Argon Crystals, Tellurium, Oxium, Nitain und mehr. Eine komplette Farming-Referenztabelle."
    },
    "/guides/standing": {
      "title": "Warframe Standing & Syndikat-Farming Guide",
      "description": "Maximiere dein tägliches Standing bei jedem Warframe-Syndikat und jeder Open-World-Fraktion. Wie das Reputationslimit funktioniert und die schnellsten Wege, es auszureizen."
    },
    "/guides/mods": {
      "title": "Warframe Mods Guide — Wichtige Mods & Überleben",
      "description": "Wie Modding in Warframe funktioniert, die unverzichtbaren Mods und Shield-Gating, um nicht zu sterben. Verstehe Mod-Kapazität, Polaritäten und die Schadensmultiplikatoren."
    },
    "/guides/helminth": {
      "title": "Warframe Helminth Guide — Subsume & beste Fähigkeiten",
      "description": "Wie das Warframe-Helminth-System funktioniert: Freischalten, Fähigkeiten subsumieren und die besten Kräfte für deine Frames. Buildcrafting erklärt."
    },
    "/guides/arcanes": {
      "title": "Warframe Arcanes Guide — Beste Arcanes & Farmen",
      "description": "Was Arcanes in Warframe bewirken, wie du sie levelst, wo sie droppen und die essenziellen Arcanes, die sich zu farmen lohnen. Verstärke deine Frames, Waffen und Operator."
    },
    "/guides/riven": {
      "title": "Warframe Riven Mods erklärt — Disposition & Würfeln",
      "description": "Alles über Warframe Riven Mods: Disposition, Würfeln mit Kuva, Bewertung, verschleierte Rivens und warum schlechte Rivens billiges Endo sind. Grundlagen des Riven-Handels."
    },
    "/guides/steel-path": {
      "title": "Warframe Steel Path Guide — Freischalten & Essence",
      "description": "Wie du den Steel Path in Warframe freischaltest, ihn überlebst und Steel Essence für Incarnon-Adapter, Arcanes, Kuva und mehr farmst. Der Guide zu den Hard-Mode-Belohnungen."
    },
    "/guides/eidolon": {
      "title": "Warframe Eidolon-Jagd Guide — Tridolon-Grundlagen",
      "description": "Wie du in Warframe Eidolons jagst: Amps, der Meta-Squad und der Weg vom Solo-Teralyst zum vollen Tridolon. Farme Arcanes und Focus schnell."
    },
    "/guides/railjack": {
      "title": "Warframe Railjack Guide — Freischalten & Intrinsics",
      "description": "Wie du Railjack in Warframe freischaltest und nutzt: Baue dein Schiff, level Intrinsics und mach den Weltraumkampf zum Affinität- und Ressourcen-Farm."
    },
    "/guides/duviri": {
      "title": "Warframe Duviri Paradox Guide — Circuit & Decrees",
      "description": "Wie das Duviri Paradox in Warframe funktioniert: der Roguelike Circuit, Decrees und die wöchentlichen Warframe- und Incarnon-Belohnungen. Von Anfang an spielbar."
    },
    "/guides/archon-shards": {
      "title": "Warframe Archon Shards Guide — Farming & beste Werte",
      "description": "Was Archon Shards in Warframe bewirken, wie du sie in der wöchentlichen Archon Hunt farmst und welche Werte du priorisieren solltest. Der Endgame-Power-Boost erklärt."
    },
    "/guides/tier-list": {
      "title": "Warframe Tier-Liste 2026 — So liest du sie richtig",
      "description": "Warum sich Warframe Tier-Listen widersprechen, was „gut“ je nach Aktivität wirklich bedeutet und ein paar durchweg starke Frames. Baue, was dir Spaß macht, nicht nur die Meta."
    }
  },
  "fr": {
    "/guides": {
      "title": "Guides Warframe — Farm, Builds, Platine & Débutants",
      "description": "Tous les guides Warframe au même endroit : aide aux nouveaux joueurs, farm de platine et de ressources, builds, endgame et une FAQ consultable. Basé sur r/Warframe, gratuit pour les Tenno."
    },
    "/guides/farming": {
      "title": "Hub de Farm Warframe — Objet, Ressource ou Monnaie",
      "description": "Que voulez-vous farmer ? Cherchez par type — Orokin Cells, Kuva, pièces Prime, Argon, crédits, Endo — et accédez au meilleur farm. Tous les guides de farm Warframe dans un seul hub."
    },
    "/faq": {
      "title": "FAQ Warframe — Réponses aux questions que tous se posent",
      "description": "La FAQ r/Warframe, avec les réponses : frames de départ, gagner du platine, trading, farm, Steel Path, mods et plus. Consultable, avec liens croisés et toujours gratuite."
    },
    "/creators": {
      "title": "Meilleurs YouTubeurs & créateurs Warframe à suivre",
      "description": "Un annuaire vérifié des meilleurs créateurs de contenu Warframe : maîtres du build, faiseurs de tier list, spécialistes du farm et guides pour débutants à suivre sur YouTube."
    },
    "/tools": {
      "title": "Annuaire des outils Warframe — Meilleures apps & sites",
      "description": "L'annuaire vérifié des meilleurs outils Warframe tiers : trading, planificateurs de build, tables de drop, calculateurs de riven, suivi de l'état du monde, apps et bots Discord."
    },
    "/tools/best": {
      "title": "Meilleurs outils Warframe 2026 — Classés & vérifiés",
      "description": "Les meilleurs outils Warframe tiers, classés et vérifiés : trading et vérificateurs de prix, planificateurs de build, tables de drop, traqueurs de riven et d'état du monde. Que choisir et pourquoi."
    },
    "/guides/new-player": {
      "title": "Guide Warframe nouveau joueur 2026 : par où commencer",
      "description": "Un guide Warframe complet pour débutants : par où commencer, comment fonctionne la carte des étoiles, quelle frame farmer et les erreurs à éviter. Bien démarrer Warframe."
    },
    "/guides/beginner-warframes": {
      "title": "Meilleures Warframes débutant 2026 — Laquelle choisir",
      "description": "Quelle Warframe de départ choisir (Excalibur, Mag, Volt), quelle frame farmer en premier (Rhino) et où trouver les frames faciles du début. Une feuille de route pour débutants."
    },
    "/guides/progression": {
      "title": "Guide de progression Warframe 2026 — La suite à faire",
      "description": "La feuille de route de progression Warframe : carte des étoiles, Junctions, Mastery Rank et une checklist étape par étape de la suite à faire. Ne soyez plus perdu, Tenno."
    },
    "/guides/mastery-rank": {
      "title": "Guide Mastery Rank Warframe — XP rapide & affinité",
      "description": "Ce que débloque le Mastery Rank, comment fonctionne l'affinité et son partage, et les moyens les plus rapides de monter armes et frames dans Warframe. Montez votre MR efficacement."
    },
    "/guides/quests": {
      "title": "Ordre des quêtes Warframe — Scénario (peu de spoilers)",
      "description": "L'ordre recommandé pour jouer les quêtes scénario de Warframe, de Vor's Prize à The New War et 1999 — quelle quête débloque quoi, avec un minimum de spoilers."
    },
    "/guides/platinum": {
      "title": "Comment gagner du platine dans Warframe (free-to-play)",
      "description": "Gagnez du platine Warframe gratuitement : ce qui se vend, comment marche le trading et comment fixer le prix des pièces Prime, mods et rivens. Le farm de platine free-to-play expliqué."
    },
    "/guides/credits": {
      "title": "Farm de crédits Warframe — Meilleures méthodes & nœuds",
      "description": "Les meilleurs farms de crédits Warframe par étape — The Index, Profit-Taker et boosters — et d'où viennent les millions. Farmez des crédits vite et sûrement."
    },
    "/guides/focus": {
      "title": "Guide de farm de Focus Warframe — Meilleures méthodes",
      "description": "Comment farmer le Focus dans Warframe : débloquez l'Operator, choisissez une école et utilisez les meilleurs farms de Focus, lentilles et orbes de convergence. Montez vos écoles efficacement."
    },
    "/guides/kuva": {
      "title": "Guide de farm de Kuva Warframe — Méthodes rapides",
      "description": "Les meilleures façons de farmer le Kuva dans Warframe pour re-roll vos rivens et les armes Kuva — missions Survie, Siphon et Déluge, boosters et taux réalistes."
    },
    "/guides/relics": {
      "title": "Guide de farm de Relic & Void Trace Warframe",
      "description": "Comment fonctionnent les Void Relics et Void Traces dans Warframe : ouvrir les fissures, raffiner en Radiant, récompenses partagées et farm efficace de pièces Prime."
    },
    "/guides/resources": {
      "title": "Farm de ressources Warframe — Où tout farmer",
      "description": "Où farmer chaque ressource clé de Warframe : Orokin Cells, Neurodes, Argon Crystals, Tellurium, Oxium, Nitain et plus. Un tableau de référence complet pour le farm."
    },
    "/guides/standing": {
      "title": "Guide de farm de réputation & Syndicate Warframe",
      "description": "Atteignez votre plafond de réputation quotidien dans chaque Syndicate et faction en monde ouvert. Comment marche le plafond et les moyens les plus rapides de le maximiser."
    },
    "/guides/mods": {
      "title": "Guide des mods Warframe — Mods essentiels & survie",
      "description": "Comment fonctionne le modding dans Warframe, les mods indispensables et le shield-gating pour arrêter de mourir. Comprenez la capacité de mods, les polarités et les multiplicateurs de dégâts."
    },
    "/guides/helminth": {
      "title": "Guide Helminth Warframe — Subsumer & capacités",
      "description": "Comment fonctionne le système Helminth de Warframe : le débloquer, subsumer des capacités et les meilleurs pouvoirs à greffer sur vos frames. Le buildcrafting expliqué."
    },
    "/guides/arcanes": {
      "title": "Guide des arcanes Warframe — Meilleurs arcanes & farm",
      "description": "Ce que font les arcanes dans Warframe, comment les monter, où ils tombent et les arcanes incontournables à farmer. Boostez vos frames, armes et Operator."
    },
    "/guides/riven": {
      "title": "Mods Riven Warframe expliqués — Disposition & re-roll",
      "description": "Tout sur les mods Riven de Warframe : disposition, re-roll au Kuva, notation, rivens voilés et pourquoi les mauvais rivens sont de l'Endo pas cher. Les bases du trading de Riven."
    },
    "/guides/steel-path": {
      "title": "Guide Steel Path Warframe — Débloquer & Steel Essence",
      "description": "Comment débloquer le Steel Path dans Warframe, y survivre et farmer la Steel Essence pour les adaptateurs Incarnon, arcanes, Kuva et plus. Le guide des récompenses du mode difficile."
    },
    "/guides/eidolon": {
      "title": "Guide de chasse aux Eidolon Warframe — Bases Tridolon",
      "description": "Comment chasser les Eidolon dans Warframe : amps, l'escouade meta et passer d'un Teralyst en solo au Tridolon complet. Farmez arcanes et Focus rapidement."
    },
    "/guides/railjack": {
      "title": "Guide Railjack Warframe — Débloquer, Intrinsics & farm",
      "description": "Comment débloquer et utiliser le Railjack dans Warframe : montez votre vaisseau, améliorez vos Intrinsics et transformez le combat spatial en farm d'affinité et de ressources."
    },
    "/guides/duviri": {
      "title": "Guide Duviri Paradox Warframe — Circuit & Decrees",
      "description": "Comment fonctionne le Duviri Paradox dans Warframe : le Circuit roguelike, les Decrees et les récompenses Warframe et Incarnon hebdomadaires. Jouable dès le tout début."
    },
    "/guides/archon-shards": {
      "title": "Guide Archon Shards Warframe — Farm & meilleures stats",
      "description": "Ce que font les Archon Shards dans Warframe, comment les farmer via l'Archon Hunt hebdomadaire et quelles stats prioriser. Le boost de puissance endgame expliqué."
    },
    "/guides/tier-list": {
      "title": "Tier list Warframe 2026 — Comment vraiment la lire",
      "description": "Pourquoi les tier lists Warframe se contredisent, ce que « bon » veut vraiment dire selon l'activité, et quelques frames solides en général. Jouez ce qui vous plaît, pas juste la meta."
    }
  },
  "ru": {
    "/guides": {
      "title": "Гайды по Warframe — фарм, билды, платина и старт",
      "description": "Все гайды по Warframe в одном месте: помощь новичкам, фарм платины и ресурсов, билды, эндгейм и FAQ с поиском. На основе r/Warframe, бесплатно для Tenno."
    },
    "/guides/farming": {
      "title": "Центр фарма Warframe — ищи любой предмет и ресурс",
      "description": "Что хотите фармить? Поиск по предметам — Orokin Cells, Kuva, части Prime, Argon, кредиты, Endo — и переход к лучшему фарму. Все гайды по фарму Warframe в одном центре."
    },
    "/faq": {
      "title": "FAQ по Warframe — ответы на частые вопросы",
      "description": "FAQ с r/Warframe: стартовые фреймы, заработок платины, торговля, фарм, Steel Path, моды и не только. С поиском, перекрёстными ссылками и всегда бесплатно."
    },
    "/creators": {
      "title": "Лучшие YouTube-блогеры и авторы по Warframe",
      "description": "Проверенный каталог лучших авторов контента по Warframe — мастера билдов, тир-листов, специалисты по фарму и гайды для новичков, за которыми стоит следить на YouTube."
    },
    "/tools": {
      "title": "Каталог инструментов Warframe — лучшие приложения",
      "description": "Проверенный каталог лучших сторонних инструментов Warframe: торговля, планировщики билдов, таблицы дропа, калькуляторы Riven, трекеры мира, приложения и боты Discord."
    },
    "/tools/best": {
      "title": "Лучшие инструменты Warframe 2026 — рейтинг и проверка",
      "description": "Лучшие сторонние инструменты Warframe с рейтингом и проверкой: торговля и проверка цен, планировщики билдов, таблицы дропа, трекеры Riven и мира. Что использовать и почему."
    },
    "/guides/new-player": {
      "title": "Гайд для новичков Warframe 2026: с чего начать",
      "description": "Полный гайд по Warframe для новичков: с чего начать, как работает звёздная карта, какой фрейм фармить и каких ошибок избегать. Начните Warframe правильно."
    },
    "/guides/beginner-warframes": {
      "title": "Лучшие Warframe для новичков 2026 — кого выбрать",
      "description": "Какой стартовый Warframe выбрать (Excalibur, Mag, Volt), какой фрейм фармить первым (Rhino) и где падают лёгкие ранние фреймы. Дорожная карта для новичка."
    },
    "/guides/progression": {
      "title": "Гайд по прогрессу Warframe 2026 — что делать дальше",
      "description": "Дорожная карта прогресса Warframe: звёздная карта, Junctions, Mastery Rank и пошаговый чек-лист, что делать дальше. Хватит теряться, Tenno."
    },
    "/guides/mastery-rank": {
      "title": "Гайд по Mastery Rank Warframe — быстрая прокачка",
      "description": "Что открывает Mastery Rank, как работает аффинити и его распределение, и самые быстрые способы качать оружие и фреймы в Warframe. Прокачивай MR эффективно."
    },
    "/guides/quests": {
      "title": "Порядок квестов Warframe — гайд по сюжету",
      "description": "Рекомендуемый порядок прохождения сюжетных квестов Warframe, от Vor's Prize до The New War и 1999 — какие квесты что открывают, с минимумом спойлеров."
    },
    "/guides/platinum": {
      "title": "Как заработать платину в Warframe (бесплатно)",
      "description": "Зарабатывайте платину Warframe бесплатно: что продаётся, как работает торговля и как оценивать части Prime, моды и Riven. Фарм платины без доната, объяснён."
    },
    "/guides/credits": {
      "title": "Фарм кредитов Warframe — лучшие методы и ноды",
      "description": "Лучшие фармы кредитов Warframe по этапам — The Index, Profit-Taker и бустеры — плюс откуда берутся миллионы. Фармите кредиты быстро и надёжно."
    },
    "/guides/focus": {
      "title": "Гайд по фарму Focus Warframe — лучшие методы",
      "description": "Как фармить Focus в Warframe: откройте Operator, выберите школу и используйте лучшие фармы Focus, линзы и сферы конвергенции. Качайте школы эффективно."
    },
    "/guides/kuva": {
      "title": "Гайд по фарму Kuva Warframe — быстрые методы",
      "description": "Лучшие способы фармить Kuva в Warframe для ре-роллов Riven и оружия Kuva — миссии Survival, Siphon и Flood, бустеры и реальные показатели дропа."
    },
    "/guides/relics": {
      "title": "Гайд по фарму Relic и Void Trace в Warframe",
      "description": "Как работают Void Relic и Void Trace в Warframe: вскрытие разломов, улучшение до Radiant, общие награды и эффективный фарм частей Prime."
    },
    "/guides/resources": {
      "title": "Фарм ресурсов Warframe — где фармить всё",
      "description": "Где фармить каждый ключевой ресурс Warframe: Orokin Cells, Neurodes, Argon Crystals, Tellurium, Oxium, Nitain и другое. Полная таблица-справочник по фарму."
    },
    "/guides/standing": {
      "title": "Гайд по фарму репутации и синдикатов Warframe",
      "description": "Выбивайте дневной лимит репутации во всех синдикатах и открытых фракциях Warframe. Как работает лимит репутации и самые быстрые способы его закрыть."
    },
    "/guides/mods": {
      "title": "Гайд по модам Warframe — базовые моды и выживание",
      "description": "Как работает модификация в Warframe, обязательные моды и shield-gating против смертей. Разберитесь в ёмкости модов, полярностях и множителях урона."
    },
    "/guides/helminth": {
      "title": "Гайд по Helminth Warframe — субсум и лучшие способности",
      "description": "Как работает система Helminth в Warframe: разблокировка, субсум способностей и лучшие силы для прививки фреймам. Крафт билдов, объяснён."
    },
    "/guides/arcanes": {
      "title": "Гайд по арканам Warframe — лучшие арканы и фарм",
      "description": "Что делают арканы в Warframe, как их прокачивать, где они падают и какие ключевые арканы стоит фармить. Усильте свои фреймы, оружие и Operator."
    },
    "/guides/riven": {
      "title": "Моды Riven в Warframe — disposition и ре-роллы",
      "description": "Всё о модах Riven в Warframe: disposition, ре-роллы через Kuva, оценка, скрытые Riven и почему плохие Riven — дешёвый Endo. Основы торговли Riven."
    },
    "/guides/steel-path": {
      "title": "Гайд по Steel Path Warframe — открытие и Steel Essence",
      "description": "Как открыть Steel Path в Warframe, выжить в нём и фармить Steel Essence для адаптеров Incarnon, арканов, Kuva и другого. Гайд по наградам хардмода."
    },
    "/guides/eidolon": {
      "title": "Гайд по охоте на Eidolon — основы Tridolon",
      "description": "Как охотиться на Eidolon в Warframe: усилители, мета-отряд и путь от соло-Teralyst до полного Tridolon. Фармите арканы и Focus быстро."
    },
    "/guides/railjack": {
      "title": "Гайд по Railjack Warframe — открытие, Intrinsics и фарм",
      "description": "Как открыть и использовать Railjack в Warframe: постройте корабль, качайте Intrinsics и превратите космические бои в фарм аффинити и ресурсов."
    },
    "/guides/duviri": {
      "title": "Гайд по Duviri Paradox — Circuit и Decrees",
      "description": "Как работает Duviri Paradox в Warframe: рогалик Circuit, Decrees и еженедельные награды Warframe и Incarnon. Доступно с самого старта игры."
    },
    "/guides/archon-shards": {
      "title": "Гайд по Archon Shards — фарм и лучшие статы",
      "description": "Что дают Archon Shards в Warframe, как фармить их в еженедельном Archon Hunt и какие статы приоритетны. Усиление для эндгейма, объяснено."
    },
    "/guides/tier-list": {
      "title": "Тир-лист Warframe 2026 — как его правильно читать",
      "description": "Почему тир-листы Warframe расходятся, что значит «хороший» фрейм под каждую активность, и несколько универсально сильных фреймов. Играйте в удовольствие, а не по мете."
    }
  },
  "ko": {
    "/guides": {
      "title": "Warframe 가이드 — 파밍, 빌드, 플래티넘 & 초보자 도움말",
      "description": "모든 Warframe 가이드를 한곳에: 초보자 도움말, 플래티넘 및 자원 파밍, 빌드, 엔드게임, 검색 가능한 FAQ까지. r/Warframe 기반, Tenno에게 무료."
    },
    "/guides/farming": {
      "title": "Warframe 파밍 허브 — 아이템·자원·재화 검색",
      "description": "무엇을 파밍하고 싶나요? 아이템 종류로 검색 — Orokin Cells, Kuva, prime 부품, Argon, 크레딧, Endo — 최고의 파밍처로 바로 이동. 모든 Warframe 파밍 가이드를 한 허브에."
    },
    "/faq": {
      "title": "Warframe FAQ — 모두가 묻는 질문의 답",
      "description": "r/Warframe FAQ 총정리: 스타터 프레임, 플래티넘 벌기, 거래, 파밍, Steel Path, 모드 등. 검색 가능하고 서로 연결되며 항상 무료."
    },
    "/creators": {
      "title": "팔로우할 최고의 Warframe YouTuber & 크리에이터",
      "description": "검증된 최고의 Warframe 콘텐츠 크리에이터 목록 — 빌드 마스터, 티어 리스트 제작자, 파밍 전문가, 초보자 가이드까지 YouTube에서 팔로우할 만한 채널."
    },
    "/tools": {
      "title": "Warframe 도구 디렉토리 — 최고의 커뮤니티 앱 & 사이트",
      "description": "검증된 최고의 서드파티 Warframe 도구 목록: 거래, 빌드 플래너, 드롭 테이블, Riven 계산기, 월드 스테이트 트래커, 앱, Discord 봇까지."
    },
    "/tools/best": {
      "title": "2026 최고의 Warframe 도구 — 순위 & 검증 완료",
      "description": "최고의 서드파티 Warframe 도구를 순위와 검증으로 정리: 거래·시세 조회, 빌드 플래너, 드롭 테이블, Riven 및 월드 스테이트 트래커. 무엇을 왜 써야 하는지."
    },
    "/guides/new-player": {
      "title": "Warframe 초보자 가이드 2026: 무엇부터 할까",
      "description": "완벽한 Warframe 초보자 가이드: 무엇부터 시작할지, 스타 차트 작동 방식, 어떤 프레임을 파밍할지, 피해야 할 실수까지. Warframe을 제대로 시작하세요."
    },
    "/guides/beginner-warframes": {
      "title": "2026 최고의 초보자 Warframe — 무엇을 먼저 고를까",
      "description": "어떤 스타터 Warframe을 고를지 (Excalibur, Mag, Volt), 먼저 파밍할 프레임 (Rhino), 초반 쉬운 프레임의 드롭 위치까지. 초보자를 위한 로드맵."
    },
    "/guides/progression": {
      "title": "Warframe 진행 가이드 2026 — 다음에 할 것",
      "description": "Warframe 진행 로드맵: 스타 차트, Junctions, Mastery Rank, 그리고 다음에 할 일을 단계별로 정리한 체크리스트. 더 이상 헤매지 마세요, Tenno."
    },
    "/guides/mastery-rank": {
      "title": "Warframe Mastery Rank 가이드 — 빠른 레벨링 & 어피니티",
      "description": "Mastery Rank이 해금하는 것, 어피니티 작동 및 공유 방식, Warframe에서 무기와 프레임을 가장 빠르게 레벨링하는 방법. MR을 효율적으로 올리세요."
    },
    "/guides/quests": {
      "title": "Warframe 퀘스트 순서 — 스토리 가이드 (스포일러 최소)",
      "description": "Warframe 스토리 퀘스트를 즐기는 추천 순서, Vor's Prize부터 The New War와 1999까지 — 어떤 퀘스트가 무엇을 해금하는지 최소한의 스포일러로."
    },
    "/guides/platinum": {
      "title": "Warframe 플래티넘 버는 법 (무과금)",
      "description": "Warframe 플래티넘을 무료로 버는 법: 잘 팔리는 것, 거래 방식, prime 부품·모드·Riven 가격 책정까지. 무과금 플래티넘 파밍 완벽 정리."
    },
    "/guides/credits": {
      "title": "Warframe 크레딧 파밍 — 최고의 방법 & 노드",
      "description": "단계별 최고의 Warframe 크레딧 파밍처 — The Index, Profit-Taker, 부스터 — 수백만 크레딧의 출처까지. 크레딧을 빠르고 안정적으로 파밍하세요."
    },
    "/guides/focus": {
      "title": "Warframe Focus 파밍 가이드 — 최고의 방법",
      "description": "Warframe에서 Focus를 파밍하는 법: Operator 해금, 스쿨 선택, 최고의 Focus 파밍처·렌즈·컨버전스 오브 활용까지. 스쿨을 효율적으로 레벨링하세요."
    },
    "/guides/kuva": {
      "title": "Warframe Kuva 파밍 가이드 — 빠른 방법",
      "description": "Riven 리롤과 Kuva 무기를 위한 Warframe Kuva 파밍 최고의 방법 — Survival, Siphon, Flood 미션, 부스터, 현실적인 획득량까지."
    },
    "/guides/relics": {
      "title": "Warframe Relic & Void Trace 파밍 가이드",
      "description": "Warframe에서 Void Relic과 Void Trace가 작동하는 방식: 균열 돌기, Radiant로 정제, 공유 보상, prime 부품 효율 파밍까지."
    },
    "/guides/resources": {
      "title": "Warframe 자원 파밍 — 모든 자원 파밍처",
      "description": "모든 주요 Warframe 자원의 파밍처: Orokin Cells, Neurodes, Argon Crystals, Tellurium, Oxium, Nitain 등. 완벽한 파밍 참고 표."
    },
    "/guides/standing": {
      "title": "Warframe Standing & Syndicate 파밍 가이드",
      "description": "모든 Warframe Syndicate와 오픈월드 세력에서 일일 Standing을 최대로. 평판 한도 작동 방식과 가장 빠르게 채우는 방법."
    },
    "/guides/mods": {
      "title": "Warframe 모드 가이드 — 필수 모드 & 생존력",
      "description": "Warframe 모딩 작동 방식, 필수 모드, 죽지 않기 위한 shield-gating까지. 모드 용량, 극성, 데미지 배수를 이해하세요."
    },
    "/guides/helminth": {
      "title": "Warframe Helminth 가이드 — Subsume & 최고의 능력",
      "description": "Warframe Helminth 시스템 작동 방식: 해금, 능력 Subsume, 프레임에 이식할 최고의 능력까지. 빌드 제작 완벽 정리."
    },
    "/guides/arcanes": {
      "title": "Warframe Arcane 가이드 — 최고의 Arcane & 파밍법",
      "description": "Warframe에서 Arcane의 효과, 랭크업 방법, 드롭 위치, 파밍할 가치가 있는 핵심 Arcane까지. 프레임·무기·Operator를 강화하세요."
    },
    "/guides/riven": {
      "title": "Warframe Riven 모드 완벽 설명 — Disposition & 리롤",
      "description": "Warframe Riven 모드의 모든 것: disposition, Kuva 리롤, 등급, veiled Riven, 나쁜 Riven이 값싼 Endo인 이유까지. Riven 거래 기초."
    },
    "/guides/steel-path": {
      "title": "Warframe Steel Path 가이드 — 해금 & Steel Essence",
      "description": "Warframe에서 Steel Path 해금 방법, 생존법, Incarnon 어댑터·Arcane·Kuva 등을 위한 Steel Essence 파밍까지. 하드모드 보상 가이드."
    },
    "/guides/eidolon": {
      "title": "Warframe Eidolon 사냥 가이드 — Tridolon 기초",
      "description": "Warframe에서 Eidolon을 사냥하는 법: amp, 메타 스쿼드, 솔로 Teralyst에서 풀 Tridolon까지. Arcane과 Focus를 빠르게 파밍하세요."
    },
    "/guides/railjack": {
      "title": "Warframe Railjack 가이드 — 해금, Intrinsics & 파밍",
      "description": "Warframe에서 Railjack 해금 및 사용법: 함선 제작, Intrinsics 레벨링, 우주 전투를 어피니티·자원 파밍처로 만들기."
    },
    "/guides/duviri": {
      "title": "Warframe Duviri Paradox 가이드 — Circuit & Decrees",
      "description": "Warframe에서 Duviri Paradox 작동 방식: 로그라이크 Circuit, Decrees, 주간 Warframe 및 Incarnon 보상까지. 게임 시작부터 플레이 가능."
    },
    "/guides/archon-shards": {
      "title": "Warframe Archon Shards 가이드 — 파밍 & 최고의 스탯",
      "description": "Warframe에서 Archon Shards의 효과, 주간 Archon Hunt에서 파밍하는 법, 우선순위 스탯까지. 엔드게임 강화 완벽 정리."
    },
    "/guides/tier-list": {
      "title": "Warframe 티어 리스트 2026 — 제대로 읽는 법",
      "description": "Warframe 티어 리스트가 서로 다른 이유, 콘텐츠별 '좋다'의 진짜 의미, 두루 강한 프레임 몇 가지. 메타만 좇지 말고 즐기는 프레임을 키우세요."
    }
  },
  "ja": {
    "/guides": {
      "title": "Warframeガイド — 周回・ビルド・プラチナ・初心者向け",
      "description": "Warframeの全ガイドを一箇所に。初心者向け解説、プラチナ稼ぎとリソース周回、ビルド、エンドゲーム、検索可能なFAQ。r/Warframeに基づき、Tennoに無料で提供。"
    },
    "/guides/farming": {
      "title": "Warframe周回ハブ — アイテム・リソース・通貨を検索",
      "description": "何を周回する？アイテム別に検索 — Orokin Cells、Kuva、Primeパーツ、Argon、クレジット、Endo — 最適な周回先へ。Warframeの全周回ガイドを一つのハブに。"
    },
    "/faq": {
      "title": "Warframe FAQ — みんなが尋ねる疑問への回答",
      "description": "r/WarframeのFAQに回答：スターターフレーム、プラチナ稼ぎ、トレード、周回、Steel Path、MODなど。検索可能でリンク付き、いつでも無料。"
    },
    "/creators": {
      "title": "おすすめWarframe YouTuber・コンテンツクリエイター",
      "description": "厳選したWarframeコンテンツクリエイター一覧 — ビルドの達人、ティアリスト制作者、周回のスペシャリスト、初心者ガイドなど、YouTubeでフォローすべき人たち。"
    },
    "/tools": {
      "title": "Warframeツール一覧 — おすすめコミュニティアプリ・サイト",
      "description": "厳選したサードパーティ製Warframeツール一覧：トレード、ビルドプランナー、ドロップテーブル、Riven計算ツール、ワールドステート追跡、アプリ、Discordボット。"
    },
    "/tools/best": {
      "title": "Warframeおすすめツール2026 — ランキング＆検証済み",
      "description": "おすすめのサードパーティ製Warframeツールをランキング＆検証：トレード・価格チェッカー、ビルドプランナー、ドロップテーブル、Riven・ワールドステート追跡。何をなぜ使うか。"
    },
    "/guides/new-player": {
      "title": "Warframe初心者ガイド2026：まず何をすべきか",
      "description": "Warframe初心者向け完全ガイド：まず何をするか、スターチャートの仕組み、どのフレームを周回すべきか、避けるべき失敗。正しい始め方を解説。"
    },
    "/guides/beginner-warframes": {
      "title": "初心者おすすめWarframe 2026 — 最初に選ぶべきフレーム",
      "description": "最初に選ぶべきスターターWarframe（Excalibur、Mag、Volt）、最初に周回すべきフレーム（Rhino）、序盤の入手しやすいフレームのドロップ先。初心者向けロードマップ。"
    },
    "/guides/progression": {
      "title": "Warframe進行ガイド2026 — 次に何をすべきか",
      "description": "Warframeの進行ロードマップ：スターチャート、Junction、Mastery Rank、次にやることの段階別チェックリスト。もう迷わない、Tenno。"
    },
    "/guides/mastery-rank": {
      "title": "Warframe Mastery Rankガイド — 高速レベル上げとアフィニティ",
      "description": "Mastery Rankで解放される要素、アフィニティの仕組みと共有、武器とフレームを最速でレベル上げする方法。MRを効率的に上げよう。"
    },
    "/guides/quests": {
      "title": "Warframeクエスト順 — ストーリーガイド（ネタバレ控えめ）",
      "description": "Warframeのストーリークエストのおすすめ進行順、Vor's PrizeからThe New War、1999まで — どのクエストが何を解放するか、ネタバレ最小限で解説。"
    },
    "/guides/platinum": {
      "title": "Warframeでのプラチナの稼ぎ方（無課金）",
      "description": "Warframeのプラチナを無料で稼ぐ：何が売れるか、トレードの仕組み、Primeパーツ・MOD・Rivenの値付け方。無課金プラチナ稼ぎを解説。"
    },
    "/guides/credits": {
      "title": "Warframeクレジット周回 — おすすめの方法とノード",
      "description": "段階別のおすすめクレジット周回 — The Index、Profit-Taker、ブースター — 数百万を稼ぐ場所も。クレジットを速く確実に周回。"
    },
    "/guides/focus": {
      "title": "Warframeフォーカス周回ガイド — おすすめの方法",
      "description": "Warframeでフォーカスを周回する方法：Operatorの解放、学派選び、最適なフォーカス周回・レンズ・コンバージェンス。学派を効率的にレベル上げ。"
    },
    "/guides/kuva": {
      "title": "Warframe Kuva周回ガイド — 高速な方法",
      "description": "WarframeでKuvaを周回する最適な方法。Rivenの振り直しやKuva武器向け — 耐久・Siphon・Floodミッション、ブースター、現実的な効率。"
    },
    "/guides/relics": {
      "title": "Warframe Relic・Void Trace周回ガイド",
      "description": "WarframeのVoid RelicとVoid Traceの仕組み：亀裂の攻略、Radiantへの精製、報酬の共有、Primeパーツの効率周回。"
    },
    "/guides/resources": {
      "title": "Warframeリソース周回 — 全素材の周回場所",
      "description": "Warframeの主要リソースの周回場所：Orokin Cells、Neurodes、Argon Crystals、Tellurium、Oxium、Nitainなど。周回の完全リファレンス表。"
    },
    "/guides/standing": {
      "title": "Warframe名声・Syndicate周回ガイド",
      "description": "全SyndicateとオープンワールドのファクションでWarframeの一日の名声を上限まで稼ぐ。名声上限の仕組みと最速で上限に達する方法。"
    },
    "/guides/mods": {
      "title": "Warframe MODガイド — 必須MODと生存性",
      "description": "WarframeのMODの仕組み、必携MOD、死なないためのシールドゲート。MOD容量、極性、ダメージ倍率を理解しよう。"
    },
    "/guides/helminth": {
      "title": "Warframe Helminthガイド — アビリティ移植とおすすめ能力",
      "description": "WarframeのHelminthシステムの仕組み：解放方法、アビリティの移植、フレームに移植すべきおすすめの能力。ビルド構築を解説。"
    },
    "/guides/arcanes": {
      "title": "Warframeアルケインガイド — おすすめアルケインと周回方法",
      "description": "Warframeでアルケインの効果、ランクの上げ方、ドロップ場所、周回する価値のある定番アルケイン。フレーム・武器・Operatorを強化しよう。"
    },
    "/guides/riven": {
      "title": "Warframe Riven MOD解説 — ディスポジションと振り直し",
      "description": "Warframe Riven MODの全て：ディスポジション、Kuvaでの振り直し、評価、Veiled Riven、なぜ弱いRivenが安いEndoになるのか。Rivenトレードの基本。"
    },
    "/guides/steel-path": {
      "title": "Warframe Steel Pathガイド — 解放とSteel Essence",
      "description": "WarframeでSteel Pathを解放し、生き延び、Incarnonアダプター・アルケイン・Kuvaなどのために Steel Essenceを周回する方法。ハードモード報酬ガイド。"
    },
    "/guides/eidolon": {
      "title": "Warframe Eidolon狩りガイド — Tridolonの基本",
      "description": "WarframeでEidolonを狩る方法：アンプ、メタ編成、ソロTeralystからフルTridolonまで。アルケインとフォーカスを高速周回。"
    },
    "/guides/railjack": {
      "title": "Warframe Railjackガイド — 解放・Intrinsics・周回",
      "description": "WarframeでRailjackを解放して使う方法：艦を組み立て、Intrinsicsを上げ、宇宙戦闘をアフィニティとリソースの周回に変える。"
    },
    "/guides/duviri": {
      "title": "Warframe Duviri Paradoxガイド — CircuitとDecrees",
      "description": "WarframeのDuviri Paradoxの仕組み：ローグライクのCircuit、Decrees、週替わりのWarframe・Incarnon報酬。ゲーム開始直後からプレイ可能。"
    },
    "/guides/archon-shards": {
      "title": "Warframe Archon Shardsガイド — 周回とおすすめステータス",
      "description": "WarframeでArchon Shardsの効果、週替わりのArchon Huntでの周回方法、優先すべきステータス。エンドゲームの強化を解説。"
    },
    "/guides/tier-list": {
      "title": "Warframeティアリスト2026 — 正しい読み方",
      "description": "Warframeのティアリストが食い違う理由、コンテンツごとの「強い」の本当の意味、汎用的に強いフレーム。メタだけでなく好きなものをビルドしよう。"
    }
  },
  "zh-hans": {
    "/guides": {
      "title": "Warframe 攻略大全 — 刷素材、配装、白金与新手指南",
      "description": "所有 Warframe 攻略一站搞定：新手指引、白金与资源farm、配装、终局玩法及可搜索FAQ。取材自 r/Warframe，Tenno 免费畅用。"
    },
    "/guides/farming": {
      "title": "Warframe farm 中心 — 搜索任意物品、资源或货币",
      "description": "你想farm什么？按物品类型搜索——Orokin Cells、Kuva、Prime 部件、Argon、现金、Endo——直达最佳farm点。所有 Warframe farm 攻略汇于一处。"
    },
    "/faq": {
      "title": "Warframe 常见问题 FAQ — 大家都想知道的答案",
      "description": "r/Warframe 常见问题一网打尽：初始战甲、赚白金、交易、farm、Steel Path、Mod 等。可搜索、互相关联、永久免费。"
    },
    "/creators": {
      "title": "值得关注的最佳 Warframe UP主与内容作者",
      "description": "经过核实的最佳 Warframe 内容作者目录——配装大神、tier list 制作者、farm 专家与新手教学，值得在 YouTube 关注。"
    },
    "/tools": {
      "title": "Warframe 工具目录 — 最佳社区应用与网站",
      "description": "经核实的最佳第三方 Warframe 工具目录：交易、配装规划、掉落表、Riven 计算器、世界状态追踪、应用与 Discord 机器人。"
    },
    "/tools/best": {
      "title": "2026 最佳 Warframe 工具 — 排名与核实",
      "description": "经排名与核实的最佳第三方 Warframe 工具：交易与查价、配装规划、掉落表、Riven 与世界状态追踪。该用哪个、为什么用。"
    },
    "/guides/new-player": {
      "title": "2026 Warframe 新手攻略：一开始该做什么",
      "description": "完整的 Warframe 新手指南：开局该做什么、星图如何运作、先farm哪个战甲、要避开哪些坑。正确开启你的 Warframe 之旅。"
    },
    "/guides/beginner-warframes": {
      "title": "2026 最佳新手战甲 — 该先选哪一个",
      "description": "该选哪个初始 Warframe（Excalibur、Mag、Volt）、先farm哪个战甲（Rhino），以及好上手的早期战甲在哪掉。一份新手路线图。"
    },
    "/guides/progression": {
      "title": "2026 Warframe 进度攻略 — 接下来该做什么",
      "description": "Warframe 进度路线图：星图、Junctions、Mastery Rank 以及一份逐阶段的待办清单。别再迷茫了，Tenno。"
    },
    "/guides/mastery-rank": {
      "title": "Warframe Mastery Rank 攻略 — 快速练级与亲和",
      "description": "Mastery Rank 能解锁什么、亲和如何运作与共享，以及在 Warframe 中练武器和战甲最快的方法。高效提升你的 MR。"
    },
    "/guides/quests": {
      "title": "Warframe 任务顺序 — 剧情攻略（少剧透）",
      "description": "推荐的 Warframe 剧情任务通关顺序，从 Vor's Prize 到 The New War 与 1999——哪个任务解锁什么内容，剧透极少。"
    },
    "/guides/platinum": {
      "title": "Warframe 如何赚白金（免费玩家）",
      "description": "免费赚取 Warframe 白金：什么好卖、交易如何运作、如何给 Prime 部件、Mod 和 Riven 定价。免费玩家白金farm完全讲解。"
    },
    "/guides/credits": {
      "title": "Warframe 现金 farm — 最佳方法与节点",
      "description": "分阶段的最佳 Warframe 现金farm——The Index、Profit-Taker 与加成——以及百万现金从何而来。快速又稳定地farm现金。"
    },
    "/guides/focus": {
      "title": "Warframe Focus farm 攻略 — 最佳方法",
      "description": "如何在 Warframe 中farm Focus：解锁 Operator、选择流派并使用最佳 focus farm点、透镜与聚焦球。高效提升你的流派等级。"
    },
    "/guides/kuva": {
      "title": "Warframe Kuva farm 攻略 — 快速方法",
      "description": "在 Warframe 中farm Kuva 的最佳方法，用于 Riven 洗词条和 Kuva 武器——生存、Siphon 与 Flood 任务、加成与真实产出率。"
    },
    "/guides/relics": {
      "title": "Warframe Relic 与 Void Trace farm 攻略",
      "description": "Void Relic 与 Void Trace 在 Warframe 中如何运作：开裂缝、精炼至 Radiant、共享奖励，以及高效farm Prime 部件。"
    },
    "/guides/resources": {
      "title": "Warframe 资源 farm — 万物哪里farm",
      "description": "每种关键 Warframe 资源哪里farm：Orokin Cells、Neurodes、Argon Crystals、Tellurium、Oxium、Nitain 等。一张完整的farm参考表。"
    },
    "/guides/standing": {
      "title": "Warframe 声望与 Syndicate farm 攻略",
      "description": "刷满每个 Warframe Syndicate 与开放世界阵营的每日声望。声望上限如何运作，以及刷满它最快的方法。"
    },
    "/guides/mods": {
      "title": "Warframe Mod 攻略 — 必备 Mod 与生存能力",
      "description": "Warframe 的 Mod 系统如何运作、必备 Mod 有哪些，以及用护盾门机制避免暴毙。搞懂 Mod 容量、极性与伤害倍率。"
    },
    "/guides/helminth": {
      "title": "Warframe Helminth 攻略 — 吞噬与最佳技能",
      "description": "Warframe 的 Helminth 系统如何运作：如何解锁、吞噬技能，以及移植到战甲上最好的技能。配装玩法完全讲解。"
    },
    "/guides/arcanes": {
      "title": "Warframe Arcane 攻略 — 最佳赋能与farm方法",
      "description": "Arcane 在 Warframe 中有什么用、如何升级、在哪掉落，以及值得farm的核心 Arcane。强化你的战甲、武器与 Operator。"
    },
    "/guides/riven": {
      "title": "Warframe Riven Mod 详解 — 倾向与洗词条",
      "description": "关于 Warframe Riven Mod 的一切：倾向、用 Kuva 洗词条、评级、蒙面 Riven，以及为什么废 Riven 是廉价 Endo。Riven 交易入门。"
    },
    "/guides/steel-path": {
      "title": "Warframe Steel Path 攻略 — 解锁与 Steel Essence",
      "description": "如何在 Warframe 中解锁 Steel Path、在其中生存，并farm Steel Essence 换取 Incarnon 适配器、Arcane、Kuva 等。困难模式奖励攻略。"
    },
    "/guides/eidolon": {
      "title": "Warframe Eidolon 狩猎攻略 — Tridolon 入门",
      "description": "如何在 Warframe 中狩猎 Eidolon：Amp、meta 阵容，以及从单刷 Teralyst 进阶到完整 Tridolon。快速farm Arcane 与 focus。"
    },
    "/guides/railjack": {
      "title": "Warframe Railjack 攻略 — 解锁、Intrinsics 与 farm",
      "description": "如何在 Warframe 中解锁并使用 Railjack：打造你的战舰、提升 Intrinsics，把太空战变成亲和与资源farm。"
    },
    "/guides/duviri": {
      "title": "Warframe Duviri Paradox 攻略 — Circuit 与 Decrees",
      "description": "Duviri Paradox 在 Warframe 中如何运作：roguelike 的 Circuit、Decrees，以及每周的 Warframe 与 Incarnon 奖励。从一开始就能玩。"
    },
    "/guides/archon-shards": {
      "title": "Warframe Archon Shards 攻略 — farm与最佳属性",
      "description": "Archon Shards 在 Warframe 中有什么用、如何从每周 Archon Hunt 中farm它们，以及该优先选哪些属性。终局强化完全讲解。"
    },
    "/guides/tier-list": {
      "title": "2026 Warframe tier list — 到底该怎么看",
      "description": "为什么各家 Warframe tier list 各执一词、每种玩法里的\"强\"到底指什么，以及几个普遍好用的战甲。玩你喜欢的，而不只是 meta。"
    }
  },
  "zh-hant": {
    "/guides": {
      "title": "Warframe 攻略大全 — 刷素材、配裝、白金與新手教學",
      "description": "所有 Warframe 攻略一站掌握：新手入門、白金與素材農場、配裝、終局內容與可搜尋 FAQ。取材自 r/Warframe，Tenno 免費使用。"
    },
    "/guides/farming": {
      "title": "Warframe 農場中心 — 搜尋任何物品、素材或貨幣",
      "description": "你想刷什麼？依物品類型搜尋 — Orokin Cells、Kuva、Prime 零件、Argon、信用點、Endo — 直接跳到最佳農場。所有 Warframe 農場攻略集於一處。"
    },
    "/faq": {
      "title": "Warframe FAQ — 人人都會問的問題全解答",
      "description": "r/Warframe 常見問題全解：起始戰甲、賺白金、交易、農場、Steel Path、模組等等。可搜尋、互相連結、永遠免費。"
    },
    "/creators": {
      "title": "最值得追蹤的 Warframe YouTuber 與內容創作者",
      "description": "經過驗證的最佳 Warframe 內容創作者名錄 — 配裝高手、Tier List 製作者、農場專家與新手攻略，值得在 YouTube 追蹤。"
    },
    "/tools": {
      "title": "Warframe 工具名錄 — 最佳社群 App 與網站",
      "description": "經過驗證的最佳第三方 Warframe 工具名錄：交易、配裝規劃、掉落表、Riven 計算機、世界狀態追蹤、App 與 Discord 機器人。"
    },
    "/tools/best": {
      "title": "2026 最佳 Warframe 工具 — 排名與驗證",
      "description": "最佳第三方 Warframe 工具，經排名與驗證：交易與查價工具、配裝規劃、掉落表、Riven 與世界狀態追蹤。該用哪個、為什麼。"
    },
    "/guides/new-player": {
      "title": "2026 Warframe 新手指南：一開始該做什麼",
      "description": "完整 Warframe 新手攻略：一開始該做什麼、星圖如何運作、該刷哪隻戰甲，以及要避開的錯誤。用正確方式開始 Warframe。"
    },
    "/guides/beginner-warframes": {
      "title": "2026 最佳新手戰甲 — 第一隻該選誰",
      "description": "該選哪隻起始 Warframe（Excalibur、Mag、Volt）、第一隻該刷哪隻（Rhino），以及好上手的前期戰甲掉在哪。新手路線圖。"
    },
    "/guides/progression": {
      "title": "2026 Warframe 進度指南 — 下一步該做什麼",
      "description": "Warframe 進度路線圖：星圖、Junctions、Mastery Rank 與一步步的下一步清單。別再迷惘了，Tenno。"
    },
    "/guides/mastery-rank": {
      "title": "Warframe Mastery Rank 指南 — 快速升級與親和力",
      "description": "Mastery Rank 解鎖什麼、親和力如何運作與共享，以及在 Warframe 中最快練武器與戰甲的方法。高效提升你的 MR。"
    },
    "/guides/quests": {
      "title": "Warframe 任務順序 — 劇情指南（低劇透）",
      "description": "建議的 Warframe 劇情任務遊玩順序，從 Vor's Prize 到 The New War 與 1999 — 哪個任務解鎖什麼，劇透最少。"
    },
    "/guides/platinum": {
      "title": "Warframe 如何賺白金（免費玩家）",
      "description": "免費賺取 Warframe 白金：什麼好賣、交易怎麼運作，以及如何為 Prime 零件、模組與 Riven 定價。免費玩家白金農場全解析。"
    },
    "/guides/credits": {
      "title": "Warframe 信用點農場 — 最佳方法與節點",
      "description": "依階段整理的最佳 Warframe 信用點農場 — The Index、Profit-Taker 與加成 — 以及百萬信用點從哪來。快速穩定刷信用點。"
    },
    "/guides/focus": {
      "title": "Warframe Focus 農場指南 — 最佳方法",
      "description": "如何在 Warframe 刷 Focus：解鎖 Operator、選擇流派並善用最佳 Focus 農場、透鏡與匯聚球。高效升級你的流派。"
    },
    "/guides/kuva": {
      "title": "Warframe Kuva 農場指南 — 快速方法",
      "description": "在 Warframe 刷 Kuva 的最佳方式，用於 Riven 洗詞條與 Kuva 武器 — 生存、Siphon 與 Flood 任務、加成與實際產出率。"
    },
    "/guides/relics": {
      "title": "Warframe Relic 與 Void Trace 農場指南",
      "description": "Warframe 中 Void Relic 與 Void Trace 如何運作：開裂縫、精煉至 Radiant、共享獎勵，以及高效刷 Prime 零件。"
    },
    "/guides/resources": {
      "title": "Warframe 素材農場 — 什麼都告訴你去哪刷",
      "description": "每種關鍵 Warframe 素材該去哪刷：Orokin Cells、Neurodes、Argon Crystals、Tellurium、Oxium、Nitain 等等。完整農場對照表。"
    },
    "/guides/standing": {
      "title": "Warframe 聲望與 Syndicate 農場指南",
      "description": "刷滿每個 Warframe Syndicate 與開放世界陣營的每日聲望。聲望上限如何運作，以及最快刷滿的方法。"
    },
    "/guides/mods": {
      "title": "Warframe 模組指南 — 必備模組與生存力",
      "description": "Warframe 模組系統如何運作、必備模組，以及靠護盾閘避免暴斃。搞懂模組容量、極性與傷害倍率。"
    },
    "/guides/helminth": {
      "title": "Warframe Helminth 指南 — 吸收與最佳技能",
      "description": "Warframe Helminth 系統如何運作：解鎖、吸收技能，以及最值得移植到戰甲上的技能。配裝玩法全解析。"
    },
    "/guides/arcanes": {
      "title": "Warframe Arcane 指南 — 最佳賦能與如何農",
      "description": "Arcane 在 Warframe 有什麼用、如何升級、掉在哪裡，以及值得刷的核心 Arcane。強化你的戰甲、武器與 Operator。"
    },
    "/guides/riven": {
      "title": "Warframe Riven 模組全解 — 傾向與洗詞條",
      "description": "關於 Warframe Riven 模組的一切：傾向、用 Kuva 洗詞條、評級、封印 Riven，以及為何爛 Riven 是廉價 Endo。Riven 交易入門。"
    },
    "/guides/steel-path": {
      "title": "Warframe Steel Path 指南 — 解鎖與 Steel Essence",
      "description": "如何在 Warframe 解鎖 Steel Path、如何存活，以及刷 Steel Essence 換 Incarnon 轉接器、Arcane、Kuva 等等。硬核模式獎勵指南。"
    },
    "/guides/eidolon": {
      "title": "Warframe Eidolon 狩獵指南 — Tridolon 入門",
      "description": "如何在 Warframe 狩獵 Eidolon：Amp、主流隊伍配置，從單刷 Teralyst 進階到完整 Tridolon。快速刷 Arcane 與 Focus。"
    },
    "/guides/railjack": {
      "title": "Warframe Railjack 指南 — 解鎖、Intrinsics 與農場",
      "description": "如何在 Warframe 解鎖並使用 Railjack：打造你的戰艦、升級 Intrinsics，把太空戰變成親和力與素材農場。"
    },
    "/guides/duviri": {
      "title": "Warframe Duviri Paradox 指南 — Circuit 與 Decrees",
      "description": "Warframe 中 Duviri Paradox 如何運作：Rogue-like 的 Circuit、Decrees，以及每週的 Warframe 與 Incarnon 獎勵。從一開始就能玩。"
    },
    "/guides/archon-shards": {
      "title": "Warframe Archon Shards 指南 — 農法與最佳屬性",
      "description": "Archon Shards 在 Warframe 有什麼用、如何從每週 Archon Hunt 農取，以及該優先選哪些屬性。終局戰力強化全解析。"
    },
    "/guides/tier-list": {
      "title": "2026 Warframe Tier List — 該怎麼正確解讀",
      "description": "為何 Warframe Tier List 各說各話、每種活動裡「強」到底是什麼意思，以及幾隻泛用強力戰甲。玩你喜歡的，別只追主流。"
    }
  },
  "pl": {
    "/guides": {
      "title": "Poradniki Warframe — Farmienie, Buildy, Platyna i Start",
      "description": "Wszystkie poradniki Warframe w jednym miejscu: pomoc dla nowych graczy, farmienie platyny i zasobów, buildy, endgame i przeszukiwalne FAQ. Oparte na r/Warframe, za darmo dla Tenno."
    },
    "/guides/farming": {
      "title": "Centrum Farmienia Warframe — Szukaj Przedmiotów i Zasobów",
      "description": "Co chcesz farmić? Szukaj po typie — Orokin Cells, Kuva, części Prime, Argon, kredyty, Endo — i przejdź do najlepszej farmy. Wszystkie poradniki do farmienia Warframe w jednym miejscu."
    },
    "/faq": {
      "title": "FAQ Warframe — Odpowiedzi na Najczęstsze Pytania",
      "description": "FAQ z r/Warframe z odpowiedziami: startowe warframe'y, zdobywanie platyny, handel, farmienie, Steel Path, mody i więcej. Przeszukiwalne, z odnośnikami i zawsze za darmo."
    },
    "/creators": {
      "title": "Najlepsi YouTuberzy i Twórcy Warframe — Kogo Obserwować",
      "description": "Zweryfikowany katalog najlepszych twórców Warframe — mistrzowie buildów, autorzy tier list, specjaliści od farmienia i poradniki dla początkujących, których warto obserwować na YouTube."
    },
    "/tools": {
      "title": "Katalog Narzędzi Warframe — Najlepsze Apki i Strony",
      "description": "Zweryfikowany katalog najlepszych narzędzi do Warframe: handel, planery buildów, tabele dropów, kalkulatory riven, trackery world-state, aplikacje i boty na Discord."
    },
    "/tools/best": {
      "title": "Najlepsze Narzędzia Warframe 2026 — Ranking i Weryfikacja",
      "description": "Najlepsze zewnętrzne narzędzia do Warframe w rankingu i po weryfikacji: handel i sprawdzanie cen, planery buildów, tabele dropów, trackery riven i world-state. Czego używać i dlaczego."
    },
    "/guides/new-player": {
      "title": "Poradnik Warframe dla Nowych Graczy 2026: Od Czego Zacząć",
      "description": "Kompletny poradnik Warframe dla początkujących: od czego zacząć, jak działa mapa gwiezdna, którego warframe'a farmić i jakich błędów unikać. Zacznij grę w Warframe dobrze."
    },
    "/guides/beginner-warframes": {
      "title": "Najlepsze Warframe'y na Start 2026 — Którego Wybrać",
      "description": "Którego startowego Warframe wybrać (Excalibur, Mag, Volt), którego warframe'a farmić najpierw (Rhino) i gdzie wypadają łatwe wczesne frame'y. Plan rozwoju dla początkujących."
    },
    "/guides/progression": {
      "title": "Poradnik Rozwoju w Warframe 2026 — Co Robić Dalej",
      "description": "Plan rozwoju w Warframe: mapa gwiezdna, Junctions, Mastery Rank i lista krok po kroku, co robić dalej. Przestań czuć się zagubiony, Tenno."
    },
    "/guides/mastery-rank": {
      "title": "Poradnik Mastery Rank w Warframe — Szybkie Levelowanie",
      "description": "Co odblokowuje Mastery Rank, jak działa affinity i jego dzielenie oraz najszybsze sposoby na levelowanie broni i warframe'ów. Podnoś MR efektywnie."
    },
    "/guides/quests": {
      "title": "Kolejność Questów w Warframe — Poradnik Fabularny",
      "description": "Zalecana kolejność questów fabularnych Warframe, od Vor's Prize przez The New War po 1999 — co odblokowują poszczególne questy, z minimum spoilerów."
    },
    "/guides/platinum": {
      "title": "Jak Zdobyć Platynę w Warframe (Za Darmo)",
      "description": "Zdobywaj platynę w Warframe za darmo: co się sprzedaje, jak działa handel i jak wyceniać części Prime, mody i riveny. Farmienie platyny bez płacenia, wyjaśnione."
    },
    "/guides/credits": {
      "title": "Farmienie Kredytów w Warframe — Najlepsze Metody",
      "description": "Najlepsze farmy kredytów w Warframe według etapu — The Index, Profit-Taker i boostery — oraz skąd biorą się miliony. Farm kredyty szybko i pewnie."
    },
    "/guides/focus": {
      "title": "Poradnik Farmienia Focus w Warframe — Najlepsze Metody",
      "description": "Jak farmić Focus w Warframe: odblokuj Operatora, wybierz szkołę i korzystaj z najlepszych farm focus, soczewek i kul convergence. Rozwijaj szkoły efektywnie."
    },
    "/guides/kuva": {
      "title": "Poradnik Farmienia Kuva w Warframe — Szybkie Metody",
      "description": "Najlepsze sposoby na farmienie Kuva w Warframe pod re-rolle rivenów i bronie Kuva — misje Survival, Siphon i Flood, boostery i realne wskaźniki."
    },
    "/guides/relics": {
      "title": "Poradnik Farmienia Relic i Void Trace w Warframe",
      "description": "Jak działają Void Relic i Void Trace w Warframe: pękanie szczelin, ulepszanie do Radiant, wspólne nagrody i efektywne farmienie części Prime."
    },
    "/guides/resources": {
      "title": "Farmienie Zasobów w Warframe — Gdzie Farmić Wszystko",
      "description": "Gdzie farmić każdy kluczowy zasób w Warframe: Orokin Cells, Neurodes, Argon Crystals, Tellurium, Oxium, Nitain i więcej. Kompletna tabela farmienia."
    },
    "/guides/standing": {
      "title": "Poradnik Farmienia Reputacji i Syndicate w Warframe",
      "description": "Wybij dzienny limit reputacji w każdym syndicate i frakcji open-world w Warframe. Jak działa limit reputacji i jak najszybciej go maksować."
    },
    "/guides/mods": {
      "title": "Poradnik Modów w Warframe — Kluczowe Mody i Przeżywalność",
      "description": "Jak działa moddowanie w Warframe, które mody są obowiązkowe i jak działa shield-gating, żeby nie ginąć. Zrozum pojemność modów, polaryzacje i mnożniki obrażeń."
    },
    "/guides/helminth": {
      "title": "Poradnik Helminth w Warframe — Subsume i Zdolności",
      "description": "Jak działa system Helminth w Warframe: odblokowanie, subsumowanie zdolności i najlepsze moce do wszczepienia w twoje warframe'y. Tworzenie buildów, wyjaśnione."
    },
    "/guides/arcanes": {
      "title": "Poradnik Arcane w Warframe — Najlepsze Arcane i Farma",
      "description": "Co robią arcane w Warframe, jak je levelować, gdzie wypadają i które podstawowe arcane warto farmić. Wzmocnij warframe'y, bronie i Operatora."
    },
    "/guides/riven": {
      "title": "Mody Riven w Warframe — Disposition i Rerolowanie",
      "description": "Wszystko o modach Riven w Warframe: disposition, rerolowanie przez Kuva, ocenianie, zawoalowane riveny i dlaczego słabe riveny to tani Endo. Podstawy handlu rivenami."
    },
    "/guides/steel-path": {
      "title": "Poradnik Steel Path w Warframe — Steel Essence",
      "description": "Jak odblokować Steel Path w Warframe, jak przetrwać i farmić Steel Essence na adaptery Incarnon, arcane, Kuva i więcej. Poradnik po nagrody z trybu hardcore."
    },
    "/guides/eidolon": {
      "title": "Poradnik Polowań na Eidolon w Warframe — Tridolon",
      "description": "Jak polować na Eidolony w Warframe: ampy, metowy skład i droga od solowego Teralyst do pełnego Tridolon. Szybko farm arcane i focus."
    },
    "/guides/railjack": {
      "title": "Poradnik Railjack w Warframe — Odblokowanie, Intrinsics",
      "description": "Jak odblokować i używać Railjack w Warframe: zbuduj statek, levuj Intrinsics i zamień walkę w kosmosie w farmę affinity i zasobów."
    },
    "/guides/duviri": {
      "title": "Poradnik Duviri Paradox w Warframe — Circuit i Decrees",
      "description": "Jak działa Duviri Paradox w Warframe: roguelike'owy Circuit, Decrees oraz cotygodniowe nagrody Warframe i Incarnon. Grywalne od samego początku."
    },
    "/guides/archon-shards": {
      "title": "Poradnik Archon Shards w Warframe — Farma i Staty",
      "description": "Co robią Archon Shards w Warframe, jak farmić je z cotygodniowego Archon Hunt i które staty priorytetyzować. Endgame'owy wzrost mocy, wyjaśniony."
    },
    "/guides/tier-list": {
      "title": "Tier Lista Warframe 2026 — Jak Ją Naprawdę Czytać",
      "description": "Dlaczego tier listy Warframe się różnią, co naprawdę znaczy „dobry\" w danej aktywności i kilka uniwersalnie mocnych warframe'ów. Graj tym, co lubisz, nie tylko metą."
    }
  },
  "it": {
    "/guides": {
      "title": "Guide Warframe — Farming, Build, Platino e Aiuto Novizi",
      "description": "Tutte le guide Warframe in un unico posto: aiuto per nuovi giocatori, farming di platino e risorse, build, endgame e una FAQ ricercabile. Basata su r/Warframe, gratis per i Tenno."
    },
    "/guides/farming": {
      "title": "Hub Farming Warframe — Cerca Qualsiasi Oggetto o Risorsa",
      "description": "Cosa vuoi farmare? Cerca per tipo di oggetto — Orokin Cells, Kuva, parti prime, Argon Crystals, crediti, Endo — e vai al farm migliore. Tutte le guide al farming Warframe in un hub."
    },
    "/faq": {
      "title": "FAQ Warframe — Risposte alle Domande di Tutti",
      "description": "Le FAQ di r/Warframe, con risposte: frame iniziali, come fare platino, trading, farming, Steel Path, mod e altro. Ricercabile, con link incrociati e sempre gratis."
    },
    "/creators": {
      "title": "I Migliori YouTuber e Content Creator di Warframe",
      "description": "Una directory verificata dei migliori content creator di Warframe — maestri delle build, creatori di tier list, specialisti del farming e guide per principianti da seguire su YouTube."
    },
    "/tools": {
      "title": "Directory Tool Warframe — App e Siti della Community",
      "description": "La directory verificata dei migliori tool Warframe di terze parti: trading, pianificatori di build, drop table, calcolatori di Riven, tracker dello stato del mondo, app e bot Discord."
    },
    "/tools/best": {
      "title": "Migliori Tool Warframe 2026 — Classificati e Verificati",
      "description": "I migliori tool Warframe di terze parti, classificati e verificati: trading e price checker, pianificatori di build, drop table, tracker di Riven e stato del mondo. Cosa usare e perché."
    },
    "/guides/new-player": {
      "title": "Guida Nuovi Giocatori Warframe 2026: Cosa Fare Prima",
      "description": "Una guida completa per principianti a Warframe: cosa fare all'inizio, come funziona la mappa stellare, quale frame farmare e gli errori da evitare. Inizia Warframe nel modo giusto."
    },
    "/guides/beginner-warframes": {
      "title": "Migliori Warframe per Principianti 2026 — Quale Scegliere",
      "description": "Quale Warframe iniziale scegliere (Excalibur, Mag, Volt), quale frame farmare per primo (Rhino) e dove droppano i frame facili di inizio gioco. La roadmap per principianti."
    },
    "/guides/progression": {
      "title": "Guida alla Progressione Warframe 2026 — Cosa Fare Dopo",
      "description": "La roadmap di progressione di Warframe: mappa stellare, Junction, Mastery Rank e una checklist passo dopo passo su cosa fare dopo. Basta sentirti perso, Tenno."
    },
    "/guides/mastery-rank": {
      "title": "Guida al Mastery Rank Warframe — Livellare e Affinità",
      "description": "Cosa sblocca il Mastery Rank, come funzionano affinità e condivisione, e i modi più veloci per livellare armi e frame in Warframe. Sali di MR in modo efficiente."
    },
    "/guides/quests": {
      "title": "Ordine Quest Warframe — Guida alla Storia (Pochi Spoiler)",
      "description": "L'ordine consigliato per giocare le quest della storia di Warframe, da Vor's Prize a The New War e 1999 — quali quest sbloccano cosa, con spoiler minimi."
    },
    "/guides/platinum": {
      "title": "Come Fare Platino in Warframe (Free-to-Play)",
      "description": "Guadagna platino Warframe gratis: cosa vendere, come funziona il trading e come prezzare parti prime, mod e Riven. Farming di platino free-to-play, spiegato."
    },
    "/guides/credits": {
      "title": "Farming di Crediti Warframe — Migliori Metodi e Nodi",
      "description": "I migliori farm di crediti Warframe per fase — The Index, Profit-Taker e booster — e da dove arrivano i milioni. Farma crediti in modo veloce e affidabile."
    },
    "/guides/focus": {
      "title": "Guida al Farming di Focus Warframe — Migliori Metodi",
      "description": "Come farmare Focus in Warframe: sblocca l'Operator, scegli una scuola e usa i migliori farm di Focus, lenti e sfere di convergenza. Livella le tue scuole in modo efficiente."
    },
    "/guides/kuva": {
      "title": "Guida al Farming di Kuva Warframe — Metodi Veloci",
      "description": "I modi migliori per farmare Kuva in Warframe per ri-tirare le Riven e le armi Kuva — missioni Sopravvivenza, Siphon e Flood, booster e rate realistici."
    },
    "/guides/relics": {
      "title": "Guida al Farming di Relic e Void Trace Warframe",
      "description": "Come funzionano Void Relic e Void Trace in Warframe: aprire le fissure, raffinare a Radiant, ricompense condivise e farming efficiente per le parti prime."
    },
    "/guides/resources": {
      "title": "Farming Risorse Warframe — Dove Farmare Tutto",
      "description": "Dove farmare ogni risorsa chiave di Warframe: Orokin Cells, Neurodes, Argon Crystals, Tellurium, Oxium, Nitain e altro. Una tabella di riferimento completa per il farming."
    },
    "/guides/standing": {
      "title": "Guida al Farming di Standing e Syndicate Warframe",
      "description": "Massimizza lo standing giornaliero con ogni syndicate e fazione open-world di Warframe. Come funziona il cap della reputazione e i modi più veloci per farlo al massimo."
    },
    "/guides/mods": {
      "title": "Guida alle Mod Warframe — Mod Essenziali e Sopravvivenza",
      "description": "Come funziona il modding in Warframe, le mod indispensabili e lo shield-gating per non morire. Capisci capacità delle mod, polarità e i moltiplicatori di danno."
    },
    "/guides/helminth": {
      "title": "Guida al Helminth Warframe — Subsume e Migliori Abilità",
      "description": "Come funziona il sistema Helminth di Warframe: sbloccarlo, assorbire abilità e i migliori poteri da innestare sui tuoi frame. Il buildcrafting, spiegato."
    },
    "/guides/arcanes": {
      "title": "Guida agli Arcani Warframe — Migliori Arcani e Come Farmarli",
      "description": "Cosa fanno gli arcani in Warframe, come livellarli, dove droppano e gli arcani fondamentali da farmare. Potenzia frame, armi e Operator."
    },
    "/guides/riven": {
      "title": "Mod Riven Warframe Spiegate — Disposizione e Roll",
      "description": "Tutto sulle mod Riven di Warframe: disposizione, roll con la Kuva, valutazione, Riven velate e perché le Riven scarse sono Endo a poco prezzo. Basi del trading di Riven."
    },
    "/guides/steel-path": {
      "title": "Guida allo Steel Path Warframe — Sblocco e Steel Essence",
      "description": "Come sbloccare lo Steel Path in Warframe, sopravvivere e farmare Steel Essence per adattatori Incarnon, arcani, Kuva e altro. La guida alle ricompense della modalità difficile."
    },
    "/guides/eidolon": {
      "title": "Guida alla Caccia agli Eidolon Warframe — Basi del Tridolon",
      "description": "Come cacciare gli Eidolon in Warframe: amp, la squad meta e passare dal Teralyst in solo al Tridolon completo. Farma arcani e Focus velocemente."
    },
    "/guides/railjack": {
      "title": "Guida al Railjack Warframe — Sblocco, Intrinsics e Farming",
      "description": "Come sbloccare e usare il Railjack in Warframe: costruisci la nave, livella gli Intrinsics e trasforma il combattimento spaziale in un farm di affinità e risorse."
    },
    "/guides/duviri": {
      "title": "Guida al Duviri Paradox Warframe — Circuit e Decrees",
      "description": "Come funziona il Duviri Paradox in Warframe: il Circuit roguelike, i Decrees e le ricompense settimanali di Warframe e Incarnon. Giocabile fin dall'inizio."
    },
    "/guides/archon-shards": {
      "title": "Guida agli Archon Shards Warframe — Farming e Migliori Stat",
      "description": "Cosa fanno gli Archon Shards in Warframe, come farmarli dall'Archon Hunt settimanale e quali stat prioritizzare. Il potenziamento endgame, spiegato."
    },
    "/guides/tier-list": {
      "title": "Tier List Warframe 2026 — Come Leggerla Davvero",
      "description": "Perché le tier list di Warframe non concordano, cosa significa davvero \"buono\" per ogni attività e alcuni frame forti in generale. Costruisci ciò che ti diverte, non solo il meta."
    }
  },
  "uk": {
    "/guides": {
      "title": "Гайди Warframe — фарм, білди, платина та поради новачкам",
      "description": "Усі гайди Warframe в одному місці: допомога новачкам, фарм платини та ресурсів, білди, ендгейм і FAQ з пошуком. На основі r/Warframe, безкоштовно для Tenno."
    },
    "/guides/farming": {
      "title": "Хаб фарму Warframe — знайди будь-який предмет чи ресурс",
      "description": "Що ви хочете фармити? Шукайте за типом — Orokin Cells, Kuva, prime-частини, Argon, кредити, Endo — і переходьте до найкращого фарму. Усі гайди фарму Warframe в одному хабі."
    },
    "/faq": {
      "title": "FAQ Warframe — відповіді на найпоширеніші запитання",
      "description": "FAQ r/Warframe з відповідями: стартові фрейми, як заробити платину, трейд, фарм, Steel Path, моди та інше. З пошуком, перехресними посиланнями й завжди безкоштовно."
    },
    "/creators": {
      "title": "Найкращі ютубери та контент-мейкери Warframe",
      "description": "Перевірений каталог найкращих контент-мейкерів Warframe — майстри білдів, автори тір-листів, фахівці з фарму та гайди для новачків, на яких варто підписатися в YouTube."
    },
    "/tools": {
      "title": "Каталог інструментів Warframe — найкращі застосунки й сайти",
      "description": "Перевірений каталог найкращих сторонніх інструментів Warframe: трейд, планувальники білдів, drop-таблиці, калькулятори Riven, трекери world-state, застосунки та Discord-боти."
    },
    "/tools/best": {
      "title": "Найкращі інструменти Warframe 2026 — рейтинг і перевірка",
      "description": "Найкращі сторонні інструменти Warframe у рейтингу та з перевіркою: трейд і перевірка цін, планувальники білдів, drop-таблиці, трекери Riven і world-state. Що використати й чому."
    },
    "/guides/new-player": {
      "title": "Гайд для новачка Warframe 2026: з чого почати",
      "description": "Повний гайд для новачків Warframe: з чого почати, як працює зоряна карта, який фрейм фармити першим і яких помилок уникати. Почніть Warframe правильно."
    },
    "/guides/beginner-warframes": {
      "title": "Найкращі Warframe для новачків 2026 — кого обрати першим",
      "description": "Який стартовий Warframe обрати (Excalibur, Mag, Volt), який фрейм фармити першим (Rhino) і де падають легкі ранні фрейми. Роадмеп для новачка."
    },
    "/guides/progression": {
      "title": "Гайд прогресії Warframe 2026 — що робити далі",
      "description": "Роадмеп прогресії Warframe: зоряна карта, Junctions, Mastery Rank і покроковий чекліст, що робити далі. Годі почуватися розгублено, Tenno."
    },
    "/guides/mastery-rank": {
      "title": "Гайд Mastery Rank Warframe — швидка прокачка й affinity",
      "description": "Що відкриває Mastery Rank, як працює affinity та її розподіл і найшвидші способи прокачати зброю та фрейми у Warframe. Ефективно піднімайте свій MR."
    },
    "/guides/quests": {
      "title": "Порядок квестів Warframe — гайд по сюжету (без спойлерів)",
      "description": "Рекомендований порядок проходження сюжетних квестів Warframe, від Vor's Prize до The New War і 1999 — які квести що відкривають, з мінімумом спойлерів."
    },
    "/guides/platinum": {
      "title": "Як заробити платину у Warframe (free-to-play)",
      "description": "Заробляйте платину Warframe безкоштовно: що продавати, як працює трейд і як оцінити prime-частини, моди та Riven. Free-to-play фарм платини зрозуміло."
    },
    "/guides/credits": {
      "title": "Фарм кредитів Warframe — найкращі методи та ноди",
      "description": "Найкращі фарми кредитів Warframe за етапами — The Index, Profit-Taker і бустери — і звідки беруться мільйони. Фармте кредити швидко й надійно."
    },
    "/guides/focus": {
      "title": "Гайд фарму Focus у Warframe — найкращі методи",
      "description": "Як фармити Focus у Warframe: розблокуйте Operator, оберіть школу й використовуйте найкращі фарми фокусу, лінзи та кулі конвергенції. Ефективно качайте школи."
    },
    "/guides/kuva": {
      "title": "Гайд фарму Kuva у Warframe — швидкі методи",
      "description": "Найкращі способи фармити Kuva у Warframe для рероллів Riven і зброї Kuva — місії Survival, Siphon і Flood, бустери та реалістичні показники."
    },
    "/guides/relics": {
      "title": "Гайд фарму Relic і Void Trace у Warframe",
      "description": "Як працюють Void Relics і Void Traces у Warframe: розкриття тріщин, рефайн до Radiant, спільні нагороди й ефективний фарм prime-частин."
    },
    "/guides/resources": {
      "title": "Фарм ресурсів Warframe — де фармити все",
      "description": "Де фармити кожен ключовий ресурс Warframe: Orokin Cells, Neurodes, Argon Crystals, Tellurium, Oxium, Nitain та інше. Повна довідкова таблиця з фарму."
    },
    "/guides/standing": {
      "title": "Гайд фарму standing і Syndicate у Warframe",
      "description": "Вибирайте денний ліміт standing у кожному Syndicate і фракції відкритого світу Warframe. Як працює ліміт репутації й найшвидші способи його вибрати."
    },
    "/guides/mods": {
      "title": "Гайд модів Warframe — ключові моди й виживання",
      "description": "Як працює моддинг у Warframe, обов'язкові моди та shield-gating, щоб не помирати. Розберіться з ємністю модів, полярностями й множниками урону."
    },
    "/guides/helminth": {
      "title": "Гайд Helminth Warframe — subsume і найкращі здібності",
      "description": "Як працює система Helminth у Warframe: розблокування, subsume здібностей і найкращі сили для щеплення на ваші фрейми. Buildcrafting зрозуміло."
    },
    "/guides/arcanes": {
      "title": "Гайд Arcanes Warframe — найкращі арканки й фарм",
      "description": "Що роблять arcanes у Warframe, як їх прокачувати, звідки вони падають і які основні арканки варто фармити. Підсильте фрейми, зброю та Operator."
    },
    "/guides/riven": {
      "title": "Riven-моди Warframe — disposition і реролл",
      "description": "Усе про Riven-моди Warframe: disposition, реролл через Kuva, грейдинг, veiled Riven і чому погані Riven — це дешеве Endo. Основи трейду Riven."
    },
    "/guides/steel-path": {
      "title": "Гайд Steel Path Warframe — розблокування й Steel Essence",
      "description": "Як розблокувати Steel Path у Warframe, вижити в ньому та фармити Steel Essence для Incarnon-адаптерів, arcanes, kuva та іншого. Гайд по нагородах хардмоду."
    },
    "/guides/eidolon": {
      "title": "Гайд полювання на Eidolon у Warframe — основи Tridolon",
      "description": "Як полювати на Eidolon у Warframe: ампи, мета-загін і шлях від соло Teralyst до повного Tridolon. Швидко фармте arcanes і focus."
    },
    "/guides/railjack": {
      "title": "Гайд Railjack Warframe — розблокування, Intrinsics і фарм",
      "description": "Як розблокувати й використовувати Railjack у Warframe: збудуйте корабель, качайте Intrinsics і перетворіть космічний бій на фарм affinity та ресурсів."
    },
    "/guides/duviri": {
      "title": "Гайд Duviri Paradox Warframe — Circuit і Decrees",
      "description": "Як працює Duviri Paradox у Warframe: рогалик Circuit, Decrees і щотижневі нагороди Warframe та Incarnon. Доступно від самого старту."
    },
    "/guides/archon-shards": {
      "title": "Гайд Archon Shards Warframe — фарм і найкращі стати",
      "description": "Що роблять Archon Shards у Warframe, як фармити їх у щотижневому Archon Hunt і які стати пріоритетні. Ендгеймовий буст сили зрозуміло."
    },
    "/guides/tier-list": {
      "title": "Тір-лист Warframe 2026 — як його правильно читати",
      "description": "Чому тір-листи Warframe розходяться, що насправді означає «хороший» для кожної активності та кілька універсально сильних фреймів. Грайте за задоволенням, а не за метою."
    }
  }
}
