// Auto-generated Warframe Knowledge Center guide content.
// Drafted grounded in r/Warframe research (reddit API) + the subreddit wiki FAQ,
// then adversarially fact-checked for evergreen accuracy. Embedded video ids were
// verified live via YouTube oEmbed. Edit freely — this is the single source for
// the /guides/focus page (rendered by <GuideArticle>).
import type { Guide } from './types'

const guide: Guide = {
  "slug": "focus",
  "eyebrow": "Knowledge Center · Focus",
  "title": "Focus Farming Guide",
  "lede": "Focus is the Operator progression system that powers your Tenno's five schools. Here's how to unlock it, generate it fast with lenses and convergence orbs, and spend it where it matters.",
  "category": "farming",
  "readMins": 9,
  "stats": [
    {
      "num": "5",
      "label": "Focus schools",
      "tone": "gold"
    },
    {
      "num": "10x",
      "label": "Convergence multiplier",
      "tone": "good"
    },
    {
      "num": "45s",
      "label": "Convergence window",
      "tone": "alt"
    },
    {
      "num": "250K",
      "label": "Starting daily cap",
      "tone": "gold"
    }
  ],
  "sections": [
    {
      "id": "what-is-focus",
      "title": "What Focus Actually Is",
      "blocks": [
        {
          "type": "p",
          "text": "**Focus** is Warframe's Operator progression system. You earn a currency called **Focus Points** and pour it into one of **five Focus schools** — passive skill trees that buff your Operator, your Warframes, and your overall economy. Focus is account-wide: the points you earn go to whichever school is currently **active**, and you unlock nodes tree by tree."
        },
        {
          "type": "p",
          "text": "You don't earn Focus by doing a special activity — you earn it as a *by-product* of affinity (XP). Install a **Focus Lens** on your gear, and a slice of the affinity that gear earns is siphoned off as Focus. That's the whole loop: kill enemies, gain affinity, convert a percentage to Focus, spend it on passives. The rest of this guide is about making that trickle into a flood."
        },
        {
          "type": "kv",
          "kv": [
            {
              "k": "Unlocked by",
              "v": "The Second Dream quest"
            },
            {
              "k": "Currency",
              "v": "Focus Points (per active school)"
            },
            {
              "k": "Schools",
              "v": "Madurai, Vazarin, Naramon, Unairu, Zenurik"
            },
            {
              "k": "Generated by",
              "v": "Focus Lenses on ranked gear + affinity"
            },
            {
              "k": "Daily reset",
              "v": "Focus cap refreshes at daily reset (00:00 UTC)"
            }
          ]
        }
      ]
    },
    {
      "id": "unlock-operator",
      "title": "Step 1: Unlock Your Operator",
      "blocks": [
        {
          "type": "p",
          "text": "Focus is gated behind the story. You cannot touch a single lens until your Operator wakes up — so the first 'Focus farm' is simply progressing the [main quests](/guides/quests)."
        },
        {
          "type": "steps",
          "steps": [
            {
              "h": "Progress the star chart to The Second Dream",
              "p": "This quest unlocks once you've cleared enough of the planetary chain. It's a required story beat, not optional — keep clearing nodes and follow the quest markers. See the [progression roadmap](/guides/progression) for the order."
            },
            {
              "h": "Complete The Second Dream",
              "p": "Finishing it introduces your Operator and unlocks the Focus screen and your first school. This is the moment Focus becomes available."
            },
            {
              "h": "Complete The War Within",
              "p": "The next major quest expands your Operator's void abilities and Transference combat. You'll want this fully done before serious Focus/Eidolon farming, since Operator power is central to both."
            },
            {
              "h": "Pick your first school (free)",
              "p": "Your first school unlocks at no cost. Every additional school costs Focus to unlock later (around 50,000 each), so choose deliberately — most players open Zenurik first (see below)."
            }
          ]
        },
        {
          "type": "tip",
          "text": "The [Duviri Paradox](/guides/duviri) gives newer players an early taste of the Drifter and some Focus-adjacent systems, but the standard, complete path to Focus is still **The Second Dream → The War Within**."
        }
      ]
    },
    {
      "id": "schools",
      "title": "The Five Focus Schools",
      "blocks": [
        {
          "type": "p",
          "text": "Only **one school is active at a time**, but you can switch freely between unlocked schools outside of missions. Each school has both school-specific nodes (active only when that school is selected) and permanent **Way-Bound** passives that apply no matter what. Here's what each one is known for:"
        },
        {
          "type": "table",
          "table": {
            "columns": [
              "School",
              "Color",
              "Signature strength",
              "Best for"
            ],
            "rows": [
              [
                "Zenurik",
                "Yellow",
                "Energy regen zone (Wellspring / Energizing Dash)",
                "Everyone — the default energy-economy pick"
              ],
              [
                "Madurai",
                "Red",
                "Amp & Void damage buffs",
                "Eidolon hunting, Operator DPS"
              ],
              [
                "Naramon",
                "Green",
                "Melee combo retention, stealth/affinity",
                "Melee builds, heavy-attack playstyles"
              ],
              [
                "Unairu",
                "White",
                "Shield & armor strip via Operator",
                "Eidolons, [Steel Path](/guides/steel-path) armor strip"
              ],
              [
                "Vazarin",
                "Blue",
                "Healing, revives, defense-target protection",
                "Support, defense/escort, Eidolon lures"
              ]
            ],
            "note": "Signature nodes and exact numbers get tuned over time — check the live wiki for the current node layout before committing a full unlock."
          }
        },
        {
          "type": "tip",
          "text": "**Unlock Zenurik first.** Its energy-regen zone fixes the single biggest early-game headache — running dry on ability energy — and it benefits every frame you'll ever play. Madurai or Unairu is the usual second pick if you're chasing Eidolons."
        }
      ]
    },
    {
      "id": "lenses",
      "title": "Focus Lenses: The Engine",
      "blocks": [
        {
          "type": "p",
          "text": "A **Focus Lens** is installed on a piece of gear and bound to one school. Once installed, it converts a percentage of that item's affinity into Focus for that school. **Install lenses on fully-ranked (rank 30) gear** — that way all of the affinity it earns counts toward Focus conversion instead of being 'spent' leveling the item up."
        },
        {
          "type": "p",
          "text": "Each equipped item holds its own lens: your Warframe, primary, secondary, melee, and companion can *each* carry one. A fully-lensed loadout multiplies your Focus income dramatically versus lensing a single frame."
        },
        {
          "type": "table",
          "table": {
            "columns": [
              "Lens tier",
              "Conversion (of excess affinity)",
              "Where to get it"
            ],
            "rows": [
              [
                "Lens",
                "~2%",
                "Sorties, open-world bounties, events"
              ],
              [
                "Greater Lens",
                "~3%",
                "Built from a base Lens (Market blueprint); tier 3–5 bounty rewards"
              ],
              [
                "Eidolon Lens",
                "~4.25%",
                "Built from a Greater Lens; Cetus tier-5 / Steel Path bounties or Cavia standing"
              ],
              [
                "Lua Lens",
                "~5.5% — best rate",
                "Built from an Eidolon Lens; Lua Disruption (rotation C)"
              ]
            ],
            "note": "Higher tiers are crafted by upgrading the tier below, so grabbing base Lenses early pays off. Percentages and sources shift with updates — confirm exact recipes on the live wiki."
          }
        },
        {
          "type": "warn",
          "text": "A lens **binds to a school when you install it**, and overwriting it with a new lens destroys the old one. Decide the school *before* you install — don't waste an Eidolon or Lua Lens on the wrong tree. The best lenses are built up tier by tier from a base Lens, so plan ahead before you sink resources in."
        }
      ]
    },
    {
      "id": "convergence",
      "title": "Convergence Orbs & the 10x Window",
      "blocks": [
        {
          "type": "p",
          "text": "This is the mechanic that turns a trickle into a torrent. Glowing **Convergence Orbs** spawn periodically in missions (only if you have a Focus Lens equipped). Grab one and you get a **10x Focus multiplier for 45 seconds** — every point of Focus generated in that window is multiplied tenfold, and the orb also instantly drops **5,000 Focus** into your active school on pickup. Serious Focus farming is really *convergence* farming: you stockpile kills and dump maximum affinity during that 45-second window."
        },
        {
          "type": "info",
          "text": "A common r/Warframe gripe is 'why do we still rely on convergence orbs to earn Focus?' It's a fair critique — outside the multiplier window, Focus gain is slow by design. The practical answer: pick a farm with dense, continuous kills so orbs spawn often, and route your burst damage to line up with each orb you pick up."
        },
        {
          "type": "p",
          "text": "You can only have one convergence buff active at a time, and picking up a fresh orb refreshes the timer. In fast, enemy-dense modes the orbs appear frequently enough that you're in the multiplier most of the run — which is exactly why the farms below are so much better than grinding random missions."
        }
      ]
    },
    {
      "id": "daily-cap",
      "title": "The Daily Focus Cap",
      "blocks": [
        {
          "type": "p",
          "text": "Focus has a **daily cap** — a shared ceiling on how much you can bank across all schools in a single day. It **starts at 250,000** and rises with your **Mastery Rank** (roughly +5,000 per rank), so higher-MR players have a much higher ceiling than fresh Operators. The cap resets at daily reset."
        },
        {
          "type": "warn",
          "text": "Once you hit the cap, additional Focus earned that day is **wasted**. The efficient play is to hit your cap quickly in a strong farm, then move on to other goals instead of grinding Focus you can't bank. Don't burn a double-affinity weekend running low-density missions."
        },
        {
          "type": "kv",
          "kv": [
            {
              "k": "Starting cap",
              "v": "250,000 / day (all schools combined)"
            },
            {
              "k": "Scaling",
              "v": "Rises with your Mastery Rank (~+5,000 per rank)"
            },
            {
              "k": "Reset",
              "v": "Daily reset (00:00 UTC)"
            },
            {
              "k": "Over-cap Focus",
              "v": "Lost — plan farms to cap efficiently"
            }
          ]
        }
      ]
    },
    {
      "id": "best-farms",
      "title": "Best Focus Farms",
      "blocks": [
        {
          "type": "p",
          "text": "The 'best node' shifts with every update, but the **principle is era-independent**: maximize enemy density, stay inside the convergence window, and carry a fully-lensed loadout. Any mode that stacks continuous kills into a lensed weapon while orbs keep spawning is a great Focus farm. These are the durable staples:"
        },
        {
          "type": "table",
          "table": {
            "columns": [
              "Method",
              "Why it works",
              "Notes"
            ],
            "rows": [
              [
                "Eidolon Hunts (Plains of Eidolon, night)",
                "Eidolon Shards convert straight to Focus — Brilliant ~25,000, Radiant ~40,000 to a school you choose — on top of massive affinity",
                "Needs an Amp + Operator setup; see the [Eidolon guide](/guides/eidolon)"
              ],
              [
                "Elite Sanctuary Onslaught (ESO)",
                "Nonstop, high-density kills with frequent convergence orbs — the classic Focus grind",
                "Bring a nuke frame + a fully-lensed loadout"
              ],
              [
                "High-density endless (Zariman Void modes, current endgame tilesets)",
                "Huge kill counts feed lensed weapons; orbs spawn steadily",
                "The exact 'best' node shifts by patch — check a recent video"
              ],
              [
                "Any mission + full lenses + boosters",
                "Passive Focus while you play the game normally",
                "Slower, but zero extra setup — great for casual capping"
              ]
            ]
          }
        },
        {
          "type": "p",
          "text": "Eidolons are uniquely strong because **Eidolon Shards are pure Focus** — you consume them for a fixed lump sum to a school you choose (Brilliant ~25,000, Radiant ~40,000), separate from the affinity conversion. That's why a Tridolon capture can push you toward your daily cap in one run. Learn the hunt in the [Eidolon guide](/guides/eidolon), and note the amps and arcanes you pick up along the way can be flipped for [platinum](/guides/platinum) via the [flip finder](/flip) or [screener](/screener)."
        },
        {
          "type": "tip",
          "text": "For pinpointing which node runs which mode right now, the [drop-location maps](/star-chart-3d) and the [community tools directory](/tools) (wiki, Overframe) stay current far better than any static list. Pair a recent Focus-farming video with a live wiki check before you grind."
        }
      ]
    },
    {
      "id": "spending",
      "title": "Way-Bound Nodes & Spending Focus",
      "blocks": [
        {
          "type": "p",
          "text": "Inside each school, nodes split into two kinds. **School nodes** only work while that school is your active one. **Way-Bound nodes** are permanent passives that apply *no matter which school is active* — and they're unlocked with Focus plus **Eidolon Shards**. That's a second reason Eidolons and Focus progression are tied together: the shards both fund your daily Focus and permanently bind the best passives."
        },
        {
          "type": "p",
          "text": "Because you can only run one school at a time, spend with intent rather than spreading points thin across all five:"
        },
        {
          "type": "list",
          "items": [
            "**Max your main school first** — usually Zenurik for its energy zone, since you'll have it selected most of the time.",
            "**Grab Way-Bound passives early** — they're permanent and stack across schools, so they never go to waste. Common priorities are the max-energy and Operator-survivability Way-Bounds.",
            "**Then branch into a role school** — Madurai/Unairu for Eidolons and armor strip, Naramon for melee, Vazarin for support.",
            "**Don't over-invest in a school you'll never select** — school-only nodes are dead weight unless that school is active."
          ]
        }
      ]
    },
    {
      "id": "efficiency",
      "title": "Squeeze Out More Focus",
      "blocks": [
        {
          "type": "p",
          "text": "Once the fundamentals are in place, these multipliers stack on top of each other for a much faster cap:"
        },
        {
          "type": "list",
          "items": [
            "**Lens every slot.** Frame + 3 weapons + companion is up to five lenses all converting at once. Put your best lenses on your most-used gear.",
            "**Set your active school to what you're farming.** All generated Focus goes to the *currently selected* school — double-check it before you start.",
            "**Stack affinity boosters.** A 2x Affinity Booster on top of a **Double Affinity Weekend** doubles your Focus income for the same effort.",
            "**Run a Smeeta Kavat.** Its Charm buff can roll a 2x affinity bonus — pure extra Focus in high-density farms.",
            "**Understand affinity flow.** Ability kills feed 100% to your Warframe; weapon kills split between the weapon and frame. In a squad, affinity is shared within range — so kills near you still feed your lensed gear.",
            "**Route damage to the convergence window.** Hold your burst for the 10x buff instead of spending it before you grab the orb."
          ]
        },
        {
          "type": "tip",
          "text": "New Focus farmers should also read the [Mastery Rank & affinity guide](/guides/mastery-rank) — the same leveling mechanics that rank your gear are what feed your lenses, so efficient leveling and efficient Focus farming are the same skill."
        }
      ]
    }
  ],
  "faqs": [
    {
      "q": "How do I unlock Focus in Warframe?",
      "a": "Focus unlocks when you complete **The Second Dream** quest, which wakes up your Operator and opens the Focus screen and your first school. Keep clearing the star chart until The Second Dream becomes available, then finish **The War Within** to fully develop your Operator. Until then you can't install a single lens."
    },
    {
      "q": "What's the best Focus school to unlock first?",
      "a": "**Zenurik** is the near-universal first pick because its energy-regen zone fixes early-game energy problems and helps every Warframe you'll ever play. After that, most players open **Madurai** (Amp/Operator damage for Eidolons) or **Unairu** (shield/armor strip). Your very first school is free; each additional one costs around 50,000 Focus."
    },
    {
      "q": "What's the fastest way to farm Focus?",
      "a": "Put Focus Lenses (ideally Eidolon or Lua Lenses) on your maxed frame and weapons, then grind a high-density mode like **Elite Sanctuary Onslaught** or hunt **Eidolons** on the Plains at night. Grab every **Convergence Orb** for the 10x multiplier, and stack an affinity booster plus a Smeeta Kavat. Eidolon Shards also convert straight to Focus (Brilliant ~25,000, Radiant ~40,000)."
    },
    {
      "q": "How do Focus lenses work and where do I get them?",
      "a": "A lens installs on a rank-30 item and converts a percentage of its affinity into Focus for one bound school — about 2% for a base Lens, 3% for a Greater Lens, 4.25% for an Eidolon Lens, and 5.5% for the top-tier Lua Lens. Base Lenses drop from Sorties and open-world bounties; each higher tier is built up from the one below (Greater from a Market blueprint, Eidolon from Cetus/Steel Path bounties or [Cavia standing](/guides/standing), Lua from Lua Disruption). Install on maxed gear so none of the affinity is wasted leveling."
    },
    {
      "q": "Why do I have to rely on convergence orbs for Focus?",
      "a": "By design, Focus gain is slow unless you're inside a **Convergence Orb** buff, which grants a 10x multiplier for 45 seconds (plus 5,000 Focus on pickup). It's a common community frustration, but the workaround is to farm dense, kill-heavy modes where orbs spawn often — so you spend most of the run inside the multiplier rather than chasing single orbs."
    },
    {
      "q": "Is there a daily Focus cap?",
      "a": "Yes. There's a shared daily cap across all schools that **starts at 250,000** and rises with your **Mastery Rank** (about +5,000 per rank). Once you hit it, extra Focus earned that day is wasted — so the efficient play is to cap quickly in a strong farm, then move on to other goals."
    },
    {
      "q": "Do I have to commit to just one Focus school?",
      "a": "No. You can switch freely between any schools you've unlocked outside of missions, so you're never locked in. On top of that, **Way-Bound** nodes are permanent passives that apply no matter which school is active — unlock those with Focus and Eidolon Shards and they benefit every build."
    },
    {
      "q": "What do Eidolon Shards do for Focus?",
      "a": "Eidolon Shards are effectively bottled Focus. Consuming a **Brilliant Shard** grants roughly 25,000 Focus and a **Radiant Shard** roughly 40,000, both going to a school you choose. Shards are also required to unlock permanent **Way-Bound** passives, which is why [Eidolon hunting](/guides/eidolon) is the premier Focus activity."
    }
  ],
  "videos": [
    {
      "id": "yt0L9JPkP1k",
      "title": "The top five ways to farm focus! | Warframe",
      "channel": "TheKengineer"
    },
    {
      "id": "B0ztEAfwj_Q",
      "title": "Farm Focus FASTER in Warframe 2025!",
      "channel": "Qemal TV"
    },
    {
      "id": "_Hq2VdgM6kw",
      "title": "[WARFRAME] Advanced FOCUS Guide! Eidolon Hunting Guide Episode 01",
      "channel": "KnightmareFrame"
    },
    {
      "id": "Lc_Pry-SQsA",
      "title": "Warframe Beginner Guide 2025: Easy Endo Farming, Focus Schools & Operator Unlocked | Episode 6",
      "channel": "Tipsy"
    }
  ],
  "sources": [
    {
      "label": "r/Warframe — Boosters run out soon, anyone wanna farm affinity?",
      "href": "https://reddit.com/r/Warframe/comments/1ih3nbq/boosters_run_out_soon_anyone_wanna_farm_affinity/"
    },
    {
      "label": "r/Warframe — Focus 2.0 Costs are too high",
      "href": "https://reddit.com/r/Warframe/comments/77iv8n/focus_20_costs_are_too_high/"
    },
    {
      "label": "Official Warframe Wiki",
      "href": "https://wiki.warframe.com/"
    }
  ],
  "related": [
    {
      "label": "Eidolon Hunting Guide",
      "to": "/guides/eidolon",
      "icon": "atom-variant",
      "note": "The premier Focus + Amp + Arcane farm"
    },
    {
      "label": "Syndicate Standing Guide",
      "to": "/guides/standing",
      "icon": "handshake",
      "note": "Standing buys lenses, arcanes and mods"
    },
    {
      "label": "Steel Path Guide",
      "to": "/guides/steel-path",
      "icon": "shield-sword",
      "note": "Where Unairu armor strip shines"
    },
    {
      "label": "Mastery Rank & Affinity",
      "to": "/guides/mastery-rank",
      "icon": "star-four-points",
      "note": "The XP mechanics that feed your lenses"
    },
    {
      "label": "Progression Roadmap",
      "to": "/guides/progression",
      "icon": "map-marker-path",
      "note": "Where Focus fits in your journey"
    },
    {
      "label": "Content Creators",
      "to": "/creators",
      "icon": "youtube",
      "note": "Follow the Focus-farming experts"
    }
  ],
  "updated": "2026-07-18"
}

export default guide
