/**
 * Generates a SUBSET of the Material Design Icons webfont containing only the
 * glyphs this app actually renders.
 *
 * Why: `@mdi/font` ships a 340 KB stylesheet (~7 500 icon rules) and a 396 KB
 * woff2. The stylesheet is render-blocking and the font is fetched on every
 * page, which alone costs more than the rest of the app's CSS+JS combined.
 * The app uses ~140 distinct icons, so the subset is ~10 KB of font and ~5 KB
 * of CSS.
 *
 * Output (both committed, regenerate whenever icons change):
 *   app/assets/mdi-subset.css      — @font-face + only the used `.mdi-*` rules
 *   public/fonts/mdi-subset.woff2  — subsetted font
 *
 * nuxt.config.ts aliases `@mdi/font/css/materialdesignicons.css` (the file
 * vuetify-nuxt-module injects automatically) to the generated CSS, so no
 * component or icon usage has to change.
 *
 * Run: npm run icons:subset
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import subsetFont from 'subset-font'

const ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)))
const MDI_CSS = path.join(ROOT, 'node_modules/@mdi/font/css/materialdesignicons.css')
const MDI_TTF = path.join(ROOT, 'node_modules/@mdi/font/fonts/materialdesignicons-webfont.ttf')
const OUT_CSS = path.join(ROOT, 'app/assets/mdi-subset.css')
const OUT_FONT = path.join(ROOT, 'public/fonts/mdi-subset.woff2')

// Directories scanned for `mdi-*` references. Icon names live in templates,
// composables, i18n messages and the baked JSON data files alike.
const SCAN_DIRS = ['app', 'i18n', 'server'].map((d) => path.join(ROOT, d))
const SCAN_EXT = new Set(['.vue', '.ts', '.js', '.mjs', '.json'])

// Icons Vuetify itself renders through its alias table (checkbox, sort arrow,
// dropdown caret, pagination chevrons, …). They never appear as literal
// `mdi-*` strings in this repo, so they must be added explicitly or controls
// lose their glyphs.
const VUETIFY_ALIASES = [
  'mdi-alert-circle', 'mdi-calendar', 'mdi-chevron-down', 'mdi-chevron-left',
  'mdi-chevron-right', 'mdi-chevron-up', 'mdi-close-circle', 'mdi-check',
  'mdi-check-circle', 'mdi-checkbox-blank-outline', 'mdi-checkbox-marked',
  'mdi-minus-box', 'mdi-circle', 'mdi-close', 'mdi-information',
  'mdi-menu-down', 'mdi-menu-up', 'mdi-page-first', 'mdi-page-last',
  'mdi-radiobox-blank', 'mdi-radiobox-marked', 'mdi-arrow-up', 'mdi-arrow-down',
  'mdi-arrow-left', 'mdi-arrow-right', 'mdi-star', 'mdi-star-outline',
  'mdi-star-half-full', 'mdi-eye', 'mdi-eye-off', 'mdi-plus', 'mdi-minus',
  'mdi-unfold-more-horizontal', 'mdi-paperclip', 'mdi-magnify',
  'mdi-dots-vertical', 'mdi-dots-horizontal', 'mdi-record', 'mdi-alert',
  'mdi-clock', 'mdi-clock-outline', 'mdi-chevron-double-left',
  'mdi-chevron-double-right', 'mdi-sort-ascending', 'mdi-sort-descending',
]

/** Recursively collect every `mdi-*` token that appears in the source tree. */
function collectUsed() {
  const found = new Set(VUETIFY_ALIASES)
  const walk = (dir) => {
    let entries
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true })
    } catch {
      return
    }
    for (const e of entries) {
      const p = path.join(dir, e.name)
      if (e.isDirectory()) {
        if (e.name === 'node_modules' || e.name.startsWith('.')) continue
        walk(p)
      } else if (SCAN_EXT.has(path.extname(e.name))) {
        const text = fs.readFileSync(p, 'utf8')
        for (const m of text.matchAll(/\bmdi-[a-z0-9]+(?:-[a-z0-9]+)*/g)) found.add(m[0])
      }
    }
  }
  SCAN_DIRS.forEach(walk)
  return found
}

/** name -> codepoint, parsed out of the upstream stylesheet. */
function parseCodepoints(css) {
  const map = new Map()
  for (const m of css.matchAll(/\.(mdi-[a-z0-9-]+)::before\s*\{\s*content:\s*"\\([0-9A-Fa-f]+)";/g)) {
    map.set(m[1], parseInt(m[2], 16))
  }
  return map
}

/** The helper rules (sizes, rotate/flip/spin, dark/light) that follow the icon list. */
function extractHelpers(css) {
  const start = css.indexOf('.mdi-18px.mdi-set')
  return start === -1 ? '' : css.slice(start)
}

const css = fs.readFileSync(MDI_CSS, 'utf8')
const codepoints = parseCodepoints(css)
const used = collectUsed()

const resolved = []
const missing = []
for (const name of [...used].sort()) {
  const cp = codepoints.get(name)
  if (cp === undefined) missing.push(name)
  else resolved.push([name, cp])
}

const text = resolved.map(([, cp]) => String.fromCodePoint(cp)).join('')
const subset = await subsetFont(fs.readFileSync(MDI_TTF), text, { targetFormat: 'woff2' })

fs.mkdirSync(path.dirname(OUT_FONT), { recursive: true })
fs.writeFileSync(OUT_FONT, subset)

const rules = resolved
  .map(([name, cp]) => `.${name}::before{content:"\\${cp.toString(16).toUpperCase()}"}`)
  .join('\n')

const out = `/* GENERATED by scripts/mdi-subset.mjs — do not edit. Run \`npm run icons:subset\`. */
@font-face {
  font-family: "Material Design Icons";
  src: url("/fonts/mdi-subset.woff2") format("woff2");
  font-weight: normal;
  font-style: normal;
  font-display: swap;
}

.mdi:before,
.mdi-set {
  display: inline-block;
  font: normal normal normal 24px/1 "Material Design Icons";
  font-size: inherit;
  text-rendering: auto;
  line-height: inherit;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

${rules}

${extractHelpers(css)}`

fs.writeFileSync(OUT_CSS, out)

console.log(`mdi-subset: ${resolved.length} icons -> ${(subset.length / 1024).toFixed(1)} KB woff2, ${(out.length / 1024).toFixed(1)} KB css`)
if (missing.length) console.log(`  (unknown, skipped: ${missing.join(', ')})`)
